### ISSUE TITLE
Crash with Chisel

### ISSUE THREAD

**Issue by MrNoe93** [Beyond-Reality/BeyondRealityModPack#155]
Pack Version: 2.2.1B

When using the chisel it sometimes won't allow me to choose the block from my inventory that I want. It changes it to another block from my inventory. Then other times it crashes when trying to chisel a block. 

Crash Report:
http://pastebin.com/J6aESA79

**Comment by Dominance** [comment]
This should of been fixed in newest BR 2.2.3+ Closing for now as I cannot replicate
