### ISSUE TITLE
Crash due to Electric Floodlight

### ISSUE THREAD

**Issue by Parcipal** [Beyond-Reality/BeyondRealityModPack#164]
Experienced a crash loop due to loading the Tile Entity for a electric flood ligt.
Unable to start up the Server

"INFO at de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.injectEnergy(TileEntityElectricFloodlight.java:108) ~[TileEntityElectricFloodlight.class:?]"

**Comment by Suterusu1337** [comment]
I vote to remove this mod until it is updated.  It just causes problems, doesn't add content and crashes client and server.

**Comment by Dominance** [comment]
Yeah removing from pack in 2.2.3
