### ISSUE TITLE
Iron and gold And possible others

### ISSUE THREAD

**Issue by Shazuli** [Beyond-Reality/BeyondRealityModPack#166]
I was in my iron vein and on the way back got some gold ore, but when I placed them in my "steam macerator" nothing happend. I check the usage for iron ore and it was no usage in the macerator, I got very confused and tested other ores. 
I found only iron and gold wasn't working (this test was in my survival world and didn't test alot of ores), I know this worked before.
Is this a bug or is this a feature? Because you can process iron and gold in the old grindstone from AE2.
![gold bar](https://cloud.githubusercontent.com/assets/9884180/5564838/44924d12-8ed7-11e4-9fbb-344d03619511.jpg)

**Comment by LemADEC** [comment]
Same issue happens with Silver ore

**Comment by Dominance** [comment]
Fixed in next version 2.2.3
