### ISSUE TITLE
Marble compatibility

### ISSUE THREAD

**Issue by LemADEC** [Beyond-Reality/BeyondRealityModPack#171]
Project Red Marble is the only one supported by Gregtech, notably to make Calcite Dust for use with Iron ore in the Electric blast furnace.
Chisel Marble isn't supported by Gregtech and seems to be more frequent in the world.

Could we have an ore recipe to exchange both, or at least allow to use the Chisel one with GT?

**Comment by Dominance** [comment]
If I remember correctly you used to be able to do this with a chisel from chisel.

**Comment by Dominance** [comment]
Yeah you can already do this as described above
