### ISSUE TITLE
GT Silver ore not supported in Fz

### ISSUE THREAD

**Issue by LemADEC** [Beyond-Reality/BeyondRealityModPack#174]
GT Silver ores aren't supported by Fz processing, only the ones from Moon/Mars are supported.

**Comment by Dominance** [comment]
Yeah Toss in the newest AOBD. http://www.curse.com/mc-mods/minecraft/221863-another-one-bites-the-dust There is already a config located within the pack https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/config/aobd.cfg
