### ISSUE TITLE
Tetrahedrite ore not macerating

### ISSUE THREAD

**Issue by bcg17** [Beyond-Reality/BeyondRealityModPack#175]
the stone form of tetrahedrite ore is not macerating when i put it into my steam macerator the recipe is also not in nei

**Comment by Dominance** [comment]
Must of missed this one also tied into EnderIO's Ore preference system. Will just toss in a tweaker script next BR update. If you find any other metals please let me know

**Comment by Dominance** [comment]
Fixed 2.2.3C
