### ISSUE TITLE
Overworld Redstone Ore Unusable

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#176]
Redstone ore ID 1555:810 can be macerated, but it does not come out as redstone, instead it comes out as crushed naquadah ore, which is probably not right. Reconfig is required in the scripts.

**Comment by Dominance** [comment]
OH yeah that is bad lol

**Comment by Dominance** [comment]
Fixed 2.2.3C

**Comment by TheRailfan** [comment]
You are right on top of this. Thanks!
