### ISSUE TITLE
Infused Crops - Wrong Drops

### ISSUE THREAD

**Issue by Parcipal** [Beyond-Reality/BeyondRealityModPack#177]
Just expierenced that infused crops are not dropping what they are supposed to drop.
- Fully matured Ordo Infused Crop -> 1x64 Glass instead of Ordo Infused Grain
- Fully matured Perditio Infused Crop -> 1x64 Sand instead of Perditio Infused Grain.

Don't know if it's a BR change thing, or a Thaumic Tinkerer issue.

Thanks in advance.

**Comment by Dominance** [comment]
Pretty sure this was a TT issue should be fixed in 2.2.4 Beta
