### ISSUE TITLE
Galacticraft Parachests/Ballons and Launch Controllers

### ISSUE THREAD

**Issue by crawln45** [Beyond-Reality/BeyondRealityModPack#178]
On occasion and it's very hard to replicate parachests and Ballons glitch out not allowing you to retrieve or even display sometimes your rockets. Launch Controllers lately have been sporadic at best that they actually launch and land on the launchpads. Also The rockets glitch never landing on the launchpads.
http://puu.sh/edbjh/c35739e0b1.jpg

**Comment by Dominance** [comment]
Should be fixed in 2.2.4 Beta
