### ISSUE TITLE
Powerarmor Durability

### ISSUE THREAD

**Issue by Zahanffxi** [Beyond-Reality/BeyondRealityModPack#179]
i dont know if its a bug But the power armor helmet losses durability constantly even when fully charged 
and it sems theres no way to repair is that normal ?
![powerarmor](https://cloud.githubusercontent.com/assets/10457500/5674198/df7560e4-97a6-11e4-825b-fee7dbc30ac5.jpg)

**Comment by Dominance** [comment]
Yeah this is a known issue I will check to see if there has been a update to the mod itself. If not I will attempt to get this worked out next BR version in another manner,

**Comment by Dominance** [comment]
Should be fixed in 2.2.4 Beta now using another build of MPS
