### ISSUE TITLE
Nitro diesel is too expensive

### ISSUE THREAD

**Issue by LemADEC** [Beyond-Reality/BeyondRealityModPack#180]
Nitro diesel requires 4 times more fuel than Fuel while only providing 3 times more power output. What's the point to have a complicated setup to make Nitro diesel then?

**Comment by Dominance** [comment]
384000 EU per Diesel Cell
4 Diesel Cells
= 1536000 EU

400000 EU per Nitro Diesel Cell
5 Nitro Diesel Cells
= 2000000 EU

So you gain +464000 EU per Nitro Glycerine Cell, when using BC-Fuel aka Diesel. And you get MULTIPLE Nitro Glycerine Cells, when producing it. That's extremly profitable! 

Please only open real issues. Do your research or ask in IRC

**Comment by LemADEC** [comment]
Sorry, I meant Nitro diesel requires more *oil* then Fuel and wasn't explicit enough:
1 oil cell gives 1 diesel/fuel cell
16 oil cells give 1 Glyceryl Trinitrate cell using a GT Distillery (and a lot of power)
4 oil cells and 1 Glyceryl trinitrate cell gives 5 nitro diesel cells

My issue is when producing Glyceryl trinitrate with a GT Distillery. It feels like this recipe is only there to trap players, which is 'out of place' in this pack in my opinion.
And yes, I know how to make Glyceryl trinitrate with a Chemical reactor.
