### ISSUE TITLE
Diamond block uncrafting

### ISSUE THREAD

**Issue by LemADEC** [Beyond-Reality/BeyondRealityModPack#181]
Uncrafting a diamond block use to give you 9 diamonds.
Now there's one recipe giving you 9 diamonds dusts and another giving 9 diamonds.

**Comment by Dominance** [comment]
Yeah not sure if this is a issue if there is one that gives dust and one that gives diamonds?

**Comment by LemADEC** [comment]
they are overlapping, means the result isn't predictable for players.
