### ISSUE TITLE
Dark/Blood/Ghostwood Natura bows uncraftable

### ISSUE THREAD

**Issue by LemADEC** [Beyond-Reality/BeyondRealityModPack#182]
Natura sticks can't be crafted with Gregtech saw (you get a Vanilla stick instead).
Consequently, Natura bows can't be crafted either.

Fusewood works fine. Issue only applies to Darkwood, Ghostwood and Bloodwood variations.

**Comment by Dominance** [comment]
Yes wont be fixed. Check old issues in case your create a duplicate one.
