### ISSUE TITLE
Electric Blast Furnace

### ISSUE THREAD

**Issue by AnomanderRake** [Beyond-Reality/BeyondRealityModPack#187]
Blast furnace wont work, either burns wires it shouldnt do or just turns on and off even with the right amount of eu

**Comment by crawln45** [comment]
This issue seems to be on versions 2.2.3b and c. 2.2.3b tries to burn wires going to the lv energy hatch regardless of cable size. 2.2.3c cables don't burn but 4 lv energy hatches with power won't power the blast furnace.

**Comment by AnomanderRake** [comment]
What he said

**Comment by AnomanderRake** [comment]
I have the Electric Blast Furnace set up, a lv battery box with 4 sodium and 4 lithium batteries, connected to the furnace with 12x tin cables, the cables feed into 4 lv hatches. The blast furnace either turns itself off immediately consuming the aluminium or the cables burn then it turns off. I have no idea what the problem is, Im almost positive its nothing im doing wrong, as I have had it working with the same set up. im currently using 2.2.3c.

**Comment by Dyonovan** [comment]
Can you take a screen shot or 4 of your setup. Make sure to include all sides.

**Comment by Dominance** [comment]
Should be fixed in 2.2.4 Beta how ever never did get the screen shots and could not replicate on my own.
