### ISSUE TITLE
Ender IO Farming Station

### ISSUE THREAD

**Issue by Cranzai** [Beyond-Reality/BeyondRealityModPack#189]
When I was working on an automated wheat farm I found an issue.
The farming station works just fine except for 1 thing. When it gets a hoe it uses it as expected.
However when the hoe takes 1 durability hit the farming station gives the "no hoe" error.
To be clear this only applies to hoes, axes for tree farms are just fine.

I hope I have given enough information about this issue, if not don't hesitate to ask.

**Comment by Dominance** [comment]
If you where playing on the server its because I have yet to update it to 2.2.3C which has this fixed included. Working on 2.2.4 soon I will update once I get it out.
