### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#190]
I am not sure if this is a problem on my side or not, but basically what happens is the game will start out running fine, with around 50% RAM usage. I have Soartex installed and 4096MB of RAM allocated to the game. Over a period of a an hour or two, the amount of RAM minecraft uses gets in excess of 80% and soon reaches levels that force me to shut down minecraft and restart it. I thought it was my dual core processor, but I replaced it with an Intel i7 quad core, and even though the CPU is running at around 40%, the memory still fills up. Unfortunately, FML does not log a memory leak, so I am not sure what could be causing it to do this. It only started recently once I upgraded to 2.2.3A, and it does not matter if I remove my custom mods and the texture pack. If you need more info please let me know, and I can try to see what I can dig up

**Comment by Dominance** [comment]
disable primitive mobs as its the only mod I know of with mem leak issues

**Comment by TheRailfan** [comment]
Is there possibly an update for primitive mobs that might fix this? I think it would take away a lot from the game if it was always disabled.

**Comment by Dominance** [comment]
Yeah no update as of right now

**Comment by DrStage** [comment]
I had the same problem with PrimitiveMobs, had to disable it because of the memory issue. The leak only occurred clientside when playing on a server, singleplayer was fine for me.

What custom mods do you have?
I had huge issues with PM and Enviromine.

**Comment by Ljduginski** [comment]
i removed primitive mobs and found the issue still happens :( I am able to recreate the issue by repeatably opening a few different chest in my base.  i think its whenever NEI loads maybe?  I have 2.2.3C recommended but with BOP not highlands.  It happens on my local server and single player.  Any ideas  LOVE this pack but not being able to open chests really sucks.

**Comment by Ljduginski** [comment]
i should mention that it takes 20min to an hour for the issue to get to the point that it starts to freeze the screen.  it fills the 4g of memory and after the freeze the memory drops to 3g ish.  and quickly fills back up.

**Comment by TheRailfan** [comment]
I can't get it to repeat, and it doesn't seem to be linked to any specific reason or mod, so I don't know what could be causing this, but disabling primitive mobs helped a little bit

**Comment by TheRailfan** [comment]
When the used RAM gets up past 80% or so, I will shut down the game, which can take up to 10 minutes. After I reload it, the used RAM stays at about 50% for a few hours, then climbs up to 80% within 30 minutes or so. The new processor helped some, but the RAM still fills up, even though I run at about 25% CPU usage

**Comment by TheRailfan** [comment]
Unfortunatly, 2.2.4 beta makes this much worse, so I have to stay downgraded at 2.2.3C until things get better

**Comment by TheRailfan** [comment]
Cancel my last, I forgot to disable Primitive Mobs in 2.2.4 after reinstalling it. We are looking at the same situation in 2.2.4 as was present in 2.2.3C.

**Comment by mamykin** [comment]
TheRailfan: How has it gone with this?

**Comment by TheRailfan** [comment]
Same as it always has been. Still no change in the way it runs, and unless an update has been released in the past 16 hours, than nothing will change until one comes around. It is definitely still playable, but still has the same problem

**Comment by Dyonovan** [comment]
Doing an update to 2.2.5 right now. Let me know if it still is happenening

**Comment by TheRailfan** [comment]
I still can't download 2.2.5 because it has not been released yet. Either that or my launcher decided it doesn't want to show up

**Comment by Dyonovan** [comment]
Will be released later tonight. Doing the last min testing now

**Comment by TheRailfan** [comment]
So......still no release yet? I see the post on the website, but no changelog? I thought it was supposed to be released 11 days ago

**Comment by TheRailfan** [comment]
I would like to say that this issue has been fixed in 2.2.6 for the time being, until Primitive Mobs recieves an update to get rid of the memory leak. With primitive mobs disabled, minecraft will remain open and running at about 60% memory for as long as one wants it to. This is with Soartex Fanver and a few custom mods installed. I will leave it up to you developers if you want to close the issue or not, because it is closed, but not really until primitive mobs is fixed.

**Comment by Dyonovan** [comment]
Removing primitive mobs mod in 2.2.7 as there are 2 many issues. Replacing with Dark Managerie
