### ISSUE TITLE
Free enchanting with osmotic enchanter

### ISSUE THREAD

**Issue by Namikon** [Beyond-Reality/BeyondRealityModPack#192]
I've tested this with 3 different computers, on my Server and on single player and it worked every time:
You can enchant for free with the osmotic enchanter. I don't know if it's a particular build of obsidian totems that causes this, but it doesn't matter what wand you are using, what item you do enchant nor which enchantments you choose. The enchanter pulls the vis out of thin air.

Running Version 2.2.3C from ATLauncher.
This is the setup i've used:
http://imgur.com/XmLkpyL

**Comment by Dominance** [comment]
Should be fxed in 2.2.4 Beta
