### ISSUE TITLE
Recipe for bloodwood sticks with bloodwood planks makes regular sticks

### ISSUE THREAD

**Issue by buizerd** [Beyond-Reality/BeyondRealityModPack#193]
This is probably because of the config change: "Normalized Natura woods to follow suit with the rest of wood planks" but this means that one cannot make the Bloodwood Bow (and probably neither the ghostwood, darkwood and fusewood bow). 

I tried crafting in hand, auto-crafter, workbench, ME crafting terminal

**Comment by Buuz135** [comment]
There is a recipe for bloodwood sticks, I don't know why this was closed
