### ISSUE TITLE
The "Hand of Ender" works on other planets

### ISSUE THREAD

**Issue by buizerd** [Beyond-Reality/BeyondRealityModPack#194]
With the Hand of Ender you can access a vanilla ender chest and transport items from the moon/mars to the overworld and back. Very useful, but it should not work :)

**Comment by Dominance** [comment]
Indeed it should not hummm Ill look into this

**Comment by Namikon** [comment]
Then you also should consider looking at the magic hand-mirror from thaumcraft.
You can't receive items, but you can send them to your mirror on DIM0, grab items with a hungry chest, pipe it to your Storage and so on.
Also, thaumcraft has a wand foci (Ender-Rift) that enables opening the ender-chest from everywhere.

**Comment by Crumbology** [comment]
Well technically the ender chest isn't in the overworld, it's an inventory attached to the players data, and cannot be automated with any of the mods in this pack. So all the items that can access it remotely are only the same as using a backpack, remove them all and you would still just be able to place an enderchest down unless it was completely disabled.

**Comment by shobu9** [comment]
It was intentional of the dev to make it access trough other dimensions
It was the hole purpose of the item

**Comment by Dyonovan** [comment]
Meh dont care. not changing
