### ISSUE TITLE
Hardcore Ender Expansion not working in 2.2.4 beta

### ISSUE THREAD

**Issue by og1996** [Beyond-Reality/BeyondRealityModPack#195]
With the beta version of BR - 2.2.4, hardcore ender expansion doesn't load up. In the mods folder, extracting the two .jar files out of HEE....zip fixes the problem.

**Comment by Dominance** [comment]
ohhh my mistake thought for sure I did that

**Comment by Dominance** [comment]
Fixed in 2.2.4 Beta just reinstall if you have this issue
