### ISSUE TITLE
Suggestion: Making various fuels available in Gregtech

### ISSUE THREAD

**Issue by zxexuxs** [Beyond-Reality/BeyondRealityModPack#200]
How about making fuel from different mods available for Gregtech generators.
I'm think of 
hootch, rocket fuel, fire wate from ender io 
biomass, biofuel from forestry
probably there are some more liquids...

This(spacially hootch) would be a nice alternative for renewable fuel in the early game :)

**Comment by TheRailfan** [comment]
That might make things too easy. The whole point of this mod pack is to extend gameplay, and that could fastrack you into the electrical age, kinda ruining the flow of thing

**Comment by zxexuxs** [comment]
It depends on the EU value you assign to the fuels. Or you tweak the the production of the fuel. At least for enderIO this should be easy. I dot know if there is an way to change the recepies for the forestry stuff.
By the way, renewable doesnt means it is easy to fully automate. You have to reach the electrical age bevore it is possible.
This change would give the players more freedom to play the game how they want to do it. I dont know for sure but to automate fuels production there are only bees and not everyone like them :)

**Comment by TheRailfan** [comment]
I do know that currently I have several chests of saplings that I could turn into plant balls and all that, but you really can't do anything with it after that. You can turn it into dirt, but thats about as useful as it gets. You can ferment it into biomass, but then you can't do anything with it. You would be able to automate this, quite simply actually, but you get nothing in return for the power spent. Automation is quite easy to do with certain fuels, like charcoal and methane, but others, not so much. It would be awesome to get at least something useful out of plant balls, but I don't know what that would be. Greg probably left it out cause plant balls are super easy to get and could make tons of methane very quickly. Biofuels would require much more automation though and therefore more EU per cell. Adding it to the diesel generator would probably be best. You could always put the biofuel into a biogas engine from forestry and just convert it over to GT EU, or power a quarry with it, or anyhting like that. For now, just use the other mod generators. And I am no developer, so I can't say that this will change.

**Comment by shobu9** [comment]
@TheRailfan #Balance It's pretty much that it could potentially break things, i'm sorry but for gregtech power you need to adapt to it's needs...

**Comment by TheRailfan** [comment]
Thats what I figured. GregTech is designed to add much more challenge and length to minecraft, and I suppose having a near infinite amount of saplings being turned into methane at a relatively low power requirement is probably game breaking. To the recycler it is.....

**Comment by Dyonovan** [comment]
Closing issue. Not changing
