### ISSUE TITLE
Shutter Module broken

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/BeyondRealityModPack#201]
The Shutter Module recipe from Gregtech is bugged and cannot be crafted in the assembling machine, because the Iron Door seems to have changed to ID -1 and shows the purple and black missing texture icon. Putting an iron door there instead does not start the machine. The culprit is the new version of Malisis Doors. Is there a way to fix it? Or does the author of that mod need to fix it somehow? Well, just wanted to let you know.

**Comment by TheRailfan** [comment]
I just made some shutters and did not have any problems. Maybe a screenshot would help you explain whats going on?

**Comment by spinner2727** [comment]
This bug report actually pertains to version 2.2.4 beta, not the current 2.2.3C. That probably should have been mentioned. Here's what it looks like:

![2015-02-13_19 32 41](https://cloud.githubusercontent.com/assets/5300243/6198461/bdb726ea-b3b7-11e4-8abd-dfff43eabaaf.png)

Iron door in the recipe has an id of -1.  Iron door in NEI has an ID of 330.  Somehow they're not the same iron door anymore.

![2015-02-13_19 32 48](https://cloud.githubusercontent.com/assets/5300243/6198464/f97a56e8-b3b7-11e4-90d7-2efcc471c9b7.png)

**Comment by spinner2727** [comment]
I was able to workaround this issue by re-adding the original recipes using MineTweaker and adding these lines to gregtech.zs:

```
//Shutter Recipe Fix
Assembler.addRecipe(shutterModule * 2, plateIron * 2, <minecraft:iron_door> * 1, 800, 16);
Assembler.addRecipe(shutterModule * 2, plateAluminium * 2, <minecraft:iron_door> * 1, 800, 16);
Assembler.addRecipe(shutterModule * 2, plateWroughtIron * 2, <minecraft:iron_door> * 1, 800, 16);
```

This does not get rid of the bugged recipes (you cannot remove recipes from GregTech in MineTweaker), but the proper ones exist now so you are able to craft them again.

**Comment by Buuz135** [comment]
Fixed in 2.2.5

**Comment by Dream-Master** [comment]
Malis Door cause this.

**Comment by Dyonovan** [comment]
Ok this was my mistake when I re did the gregtech minetweaker script for another fix. Will fix again for next update.

**Comment by Buuz135** [comment]
Refixed in 2.3.1
