### ISSUE TITLE
Kinetic / Wind turbines buggy/OP

### ISSUE THREAD

**Issue by Namikon** [Beyond-Reality/BeyondRealityModPack#203]
I did some research on them, and they should be disabled. See this issue here:
https://github.com/JasonMcRay/InfiTech-1.7/issues/74
I can tell that this "rotor-reset" happens with the current version if IC2 used in 2.2.3C, as I have 2 turbines on my server and they are back to 100% after the daily restart.

**Comment by Dyonovan** [comment]
Meh, im not to worried about this.
