### ISSUE TITLE
Malisis's doors curtain uncraftable, recipe conflict

### ISSUE THREAD

**Issue by erock112233** [Beyond-Reality/BeyondRealityModPack#205]
Players on my server are unable to craft curtains from the Malisis' doors mod, because the recipe conflicts with the ExU blackout curtains have the same recipe. ExU id is: 1582, and the malisis' doors curtain is 6070. The recipe for both is a door shape with wool.

**Comment by Dyonovan** [comment]
Will be fixed in 2.2.5 which I am working on right now
