### ISSUE TITLE
Cheap Vis

### ISSUE THREAD

**Issue by Shazuli** [Beyond-Reality/BeyondRealityModPack#206]
This is a bug I recently found, I don't know if it has to do with the mod or the modpack.

If you use the "Osmotic enchanter" from "Thaumic Tinker" and use a silverwood scepter inside the table, then the enchanter won't use any vis. Even when it needs over the capacity in which the wand can carry it still can enchant your tool. 
I haven't try any other kinds of wands but I think only the scepters have this bug. 
![super ultra sword kirby](https://cloud.githubusercontent.com/assets/9884180/6381913/0abc86b0-bd45-11e4-9673-21c9cc1bc673.jpg)

**Comment by Buuz135** [comment]
Fixed in 2.2.5
