### ISSUE TITLE
Error logging in console over and over.

### ISSUE THREAD

**Issue by dakamojo** [Beyond-Reality/BeyondRealityModPack#207]
Sometimes when I return to my base when I have the NEI lighting (F7) indicator turned on, I get a constant steam of errors logged to the console.  The errors happen so frequently that my client freezes for seconds at a time.

http://pastebin.com/BGhdddqg

I disconnect from the server and reconnect and everything is fine.  I figure out it was because of the lighting indicator because when I re-connect it is turned off.

**Comment by Dyonovan** [comment]
Going to close for now. Let me know if it still happens in 2.2.5 which I am working on now
