### ISSUE TITLE
Uncraftable items

### ISSUE THREAD

**Issue by GophBombardier** [Beyond-Reality/BeyondRealityModPack#209]
Hi, playing the beta version, and none of us on our server are able to craft some itams, like GT hammers. It shows up in crafting windows, but just bounces back when trying to pick it up. Doesn't matter if it's the soft hammer or the iron hammer. When read about it, i found a thread about a guy having same issues a few months ago, and didn't really recieve any answer why he got the problem. 

Edit: Tested a few things, and in Singleplayer game, it all work, but not in multiplayer.
Also, Botania flowers cover the ground in SP, but don't exist in MP?

My hammer got ID number 5915:xx

**Comment by mamykin** [comment]
Are you sure Forge is loaded?

**Comment by GophBombardier** [comment]
Ah, seems my server admin made a mistake there. True enough, forge was not loaded.

Pro tip: You, dear mamykin, is my server admin.. ;) :D
