### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Shazuli** [Beyond-Reality/BeyondRealityModPack#211]
Me and my friend was about to play Beyond Reaily when we noticed it took so long to start it. 
Well, it still loading after a hour now, the log has freezed and minecraft has the Mojang logo. My friend has the same issue. And whats strange is that none of us has done anything diffrent since last time. 
I don't know if it has to do with ATlauncher have some problems or Beyond Realiy's server. 
This isn't technicly a crash so minecraft made no crash report.
I have already try to reinstall and change to newer and older versions.
![loading](https://cloud.githubusercontent.com/assets/9884180/6712204/a12314ce-cd8b-11e4-9258-009e0760da2f.png)

**Comment by circu5Fr3ak** [comment]
Same problem here. I have been playing for about a month and was playing on my server yesterday afternoon. Logged off. Tried to start my client via ATLauncher a few hours later and same problem as Shazuli. I hadn't changed anything or done anything differently.

I have uninstalled the modpack, reinstalled, tried different versions of the modpack, tried many different java versions all to no avail. I was able to copy my log but it is quite large so I couldn't upload to pastebin. Here is a link to my oneDrive - [Beyond Reality Log](https://onedrive.live.com/redir?resid=15BA67F51C5FFA2%21105) 
The main theme of the log seems to be -

`[java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodException: cpw.mods.fml.common.event.FMLInterModComms$IMCMessage.<init>(java.lang.String, java.lang.Object)`

Really enjoying the pack! You guys have done an incredible job. Keep up the great work.

**Comment by circu5Fr3ak** [comment]
So I tried to start my client again, just now and it started fine. Hooray!  It must have been something to do with the ATLauncher because I did notice when I started the launcher that it updated. That is the only thing that has changed since I tried to start it yesterday.

Hopefully the problem is also solved for Shazuli.

**Comment by Shazuli** [comment]
I'm think youre right, this is tomorrow for me and now it start with no problems.

**Comment by Buuz135** [comment]
It was an ATLauncher issue.

**Comment by shobu9** [comment]
@Shazuli @Buuz135  Also you need to allocate alot of ram to run Beyond Reality!
And gregtech the first time launching can take an hour to load
