### ISSUE TITLE
2.2.5 - Doomlike dungeons not spawning

### ISSUE THREAD

**Issue by Tkdmaster** [Beyond-Reality/BeyondRealityModPack#214]
As of update 2.2.5, I have not managed to locate a single doomlike dungeon on any world created. I have tried both Biomes o Plenty, and default world gen, but neither seems to make a difference. 

I have also tried enabling the easy find mode for the dungeons in the config, as well as he pillar option it lists, but still nothing. I even went as far as to download an xray to search for the blocks of the dungeon, and they simply are not there. I am 99% sure they are just simply, not spawning anywhere.

**Comment by Buuz135** [comment]
I dont really know whats causing it, maybe I will try another dungeon mod as I cant find any update.

**Comment by Buuz135** [comment]
Removed DoomlikeDungeons in 2.2.7
