### ISSUE TITLE
Forestry Stamp (1n) is uncraftable due to Forestry:apatite requirement

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#215]
Version: BeyonReality 2.2.4beta
Because recipe require `Forestry:apatite` instead of generic ore-dictionary name `gemApatite`, it is impossible to craft `Forestry:stamps/0` Stamp (1n)

**Comment by leagris** [comment]
Either configure Gregtech unification target to Forestry, or add MineTweaker scripts for both Shaped crafting and Carpenter.

**Comment by Buuz135** [comment]
Fixed in 2.2.6
