### ISSUE TITLE
Client crash while browsing a Lexica Botania

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#217]
BeyondReality version 2.2.6

Crash log:
https://gist.github.com/leagris/2dafb18c617bc6922833#file-crash-2015-04-28_01-29-18-client-txt

**Comment by leagris** [comment]
Likely relate to Botania issue: Vazkii/Botania#813
It had a fix: Vazkii/Botania@11009b4

**Comment by Buuz135** [comment]
Fixed in 2.2.7
