### ISSUE TITLE
Railcraft Liquid and Solid Fuel Fireboxes Uncraftable

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#218]
Liquid and solid fueled fireboxes cannot be crafted at all. The boiler tanks are craftable, so I am assuming this was not by design, otherwise the boiler tanks would not be craftable at all. I also searched some cfg files to see if it was in there, but nothing says it should be disabled. Am I missing something, or should this be craftable?

**Comment by benscobie** [comment]
We have ran into the same problem on our 2.2.6 server, for some reason the existing Railcraft boilers also became unformed after a while but I am unsure if this is related.

**Comment by TheRailfan** [comment]
I would think it is. If it comes apart, the fireboxes are probably not the right ID, or something, so the multiblock does not register it as the right block. Not sure if this is a mod issue or a cfg issue, but I should be able to craft these things. I havent changed a thing in the configs since 2.2.6 came out, so it is not something I did I would say that your issue is directly linked to this one

**Comment by Buuz135** [comment]
It's intended.

**Comment by TheRailfan** [comment]
So, in 2.3.1, they are craftable. Is it safe to assume that this will change, or can I go ahead and build a railcraft boiler

**Comment by Dyonovan** [comment]
they are craftable now. its we gregtech that initially disabled them then did a fix so go wild :)

**Comment by TheRailfan** [comment]
God bless America. Thank you so much. Railcraft boilers are much more realistic if you ask me anyway
