### ISSUE TITLE
Factorization crash on Colossus Player hit

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#219]
* Beyond Reality 2.2.6 server installed from ATLauncher
* Factorization-1.7.10-0.8.89

##### Steps to reproduce bug:

1. Looted Lost Treasure map while breaking grass block.
1. Followed direction.
1. Found a colossus.
1. Broke the cracked block as told by map.
1. Client crashed and Colossus leaned down.
1. Get this crash anytime I try to hit these leaned down oriented blocks from the Felt Colossus.

##### Crash log:
https://gist.github.com/leagris/4ba477f7a5db3063fd2a

**Comment by leagris** [comment]
Fixed in Factorization-1.7.10-0.8.92

**Comment by Buuz135** [comment]
As you said, fixed in 2.2.7
