### ISSUE TITLE
Computronics Forestry integration server crash on incompatible dev/unstable Forestry builds

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#220]
Sooner or later Computronics mod will crash on intializing Forestry integration.

https://gist.github.com/leagris/a5729e389acdb974379e#file-crash-2015-05-08_23-14-55-server-txt

Given https://github.com/asiekierka/Computronics/issues/127
Vexatos commented 13 days ago
>  "unstable" builds won't be supported.

So, the proper work-around unsupported dev builds of Forestry within Computronics is:
config/computronics:
```yaml
    forestry {
        # Set this to false to disable Forestry bee species for OpenComputers [default: true]
        B:opencomputersBees=false
    }
```

Minor side consequence:
Missing Blocks/Items:
computronics:computronics.partsForestry

**Comment by Buuz135** [comment]
Fixed in 2.2.7
