### ISSUE TITLE
Lines not drawing in interfaces

### ISSUE THREAD

**Issue by benscobie** [Beyond-Reality/BeyondRealityModPack#222]
There seems to be a problem with interfaces not drawing lines correctly in 2.2.6. Below are two examples of the issue:

[Image 1](http://i.imgur.com/x75GOmA.png)
[Image 2](http://i.imgur.com/4sXRAVL.png)

Usually there are grey lines connecting the functions in Steve's Factory Manager and lines in the Thaumcraft book linking research nodes. They seem to draw fine just after joining the server but will disappear after a while, they will also randomly come back for a period of time before disappearing again. Somebody else that plays on our server is also having the same issue.

**Comment by Buuz135** [comment]
Fixed in 2.2.7
