### ISSUE TITLE
Invisible assassin

### ISSUE THREAD

**Issue by Shazuli** [Beyond-Reality/BeyondRealityModPack#223]
The newly added mod for BR called "Witching gadgets" has some neat equipments. My favourite is the spectral mantle which makes you completely invisible at any time, but at a cost of you not being able to kill, break stuff and interact with stuff. But if you use the terra blade from botania you can shot mana blasts from your sword and kill stuff without they even notice.
I just wanted you guys to know. 
![invisible assassin](https://cloud.githubusercontent.com/assets/9884180/7596164/01b92496-f8ec-11e4-8526-c403374aaffc.jpg)

**Comment by Dyonovan** [comment]
Thanks for the heads up
