### ISSUE TITLE
Forestry crash Ticking block entity while bees try to grow flowers on mycelium

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#224]
BeyoundReality v 2.2.7 Currently use Forestry 536-unstable witch had a known issue fixed
Relate to https://github.com/ForestryMC/ForestryMC/issues/650

Had a similar crash while having Miri bees at work:
https://gist.github.com/leagris/4c0b39a253f8eced20a9

I suggest an upgrade to latest unstable if it does not break something else.

**Comment by Buuz135** [comment]
Fixed in 2.2.8
