### ISSUE TITLE
Chest Recipe Suggestion

### ISSUE THREAD

**Issue by OH-Herobrine** [Beyond-Reality/BeyondRealityModPack#230]
In the recipe to make chests from wood blocks, it doesnt follow the basic Gregtech progression with wood. An idea to make this balanced is to make the normal 8 wood blocks in furnace shape to make 2 chests, and another 8 wood blocks with a saw in the middle to make 4 chests. Thanks for reading my suggestion

**Comment by Dyonovan** [comment]
Removed recipe in 2.3.0a
