### ISSUE TITLE
Gregtech Unification.cfg shall set ingotDarkSteel unification target to EnderIO

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#231]
EnderIO can't make use of Ore Dictionary name gt:ingotDarkSteel
https://github.com/SleepyTrousers/EnderIO/issues/2529

Unfortunately, Gregtech 5.08.18 from @Blood-Asp default to GregTech unification where all targets are set to false.
https://github.com/Blood-Asp/GT5-Unofficial/issues/34

Workaround:
in config/Gregtech/Unification.cfg
```YAML
enderio {
    B:ingotDarkSteel_false=true
}
```

**Comment by Dyonovan** [comment]
Fixed in 2.3.0
