### ISSUE TITLE
Hopper Minecart under Jabba barrels

### ISSUE THREAD

**Issue by Shoulon** [Beyond-Reality/BeyondRealityModPack#233]
After hopper carts full, it still tries to pull items from the jabba barrel, however the items vanish.

**Comment by Dyonovan** [comment]
Fixed in next Jabba release

**Comment by Dyonovan** [comment]
Still waiting for the new release

**Comment by leagris** [comment]
JABBA Has been updated

**Comment by leagris** [comment]
Jabba has been updated since.
