### ISSUE TITLE
Crash placing trans-dimesional item teleporter

### ISSUE THREAD

**Issue by RamboRambowski** [Beyond-Reality/BeyondRealityModPack#241]
I get the following crash when placing this item from IHL tools. I tried it three times and each time it crashed. Found in Beyond Reality version 2.3.0a. I didn't update to b because I saw it was only project red that got updated.

Client:
http://pastebin.com/YUBi0E3B

Server:
http://pastebin.com/zpNDb7sU

**Comment by Dyonovan** [comment]
Thanks for the info. 

Report to mod author: http://forum.industrial-craft.net/index.php?page=Thread&postID=189114#post189114

**Comment by Foghrye4** [comment]
Try new version. Also TDIT is kinda OP, you may want to disable it or make power consumption enormously high.

**Comment by Dyonovan** [comment]
Thanks for the heads up. I will check the configs when I update.

Fixed in http://ic2api.player.to:8080/job/IC2_experimental/735/

**Comment by Buuz135** [comment]
Fixed in 2.3.1

**Comment by Buuz135** [comment]
And blacklisted in dimensions
