### ISSUE TITLE
[GT Unofficial] Processing Array with electrolyzers doesn't function at intended rate

### ISSUE THREAD

**Issue by finkledoodle** [Beyond-Reality/BeyondRealityModPack#242]
Despite Blood stating that the processing array will function at the speed of 16 basic electrolyzers (when 16 basic electrolyzers are in the GUI), the processing array appears to only work at the rate of x8 electrolyzers as it will only accept 8 empty cells as input per each cycle.

**Comment by Buuz135** [comment]
Which recipe?

**Comment by Buuz135** [comment]
And are you using basic or advanced?

**Comment by finkledoodle** [comment]
this was with basic electrolyzers, attempting to electrolyze water into hydrogen (and oxygen cells). the issue is that the processing array only eats 8 cells at a time rather than the full 16, making it function at the rate of only x8 electrolyzers
