### ISSUE TITLE
D-O-B Queen produces only naquada

### ISSUE THREAD

**Issue by beef682** [Beyond-Reality/BeyondRealityModPack#243]
it only produces the last item in the comb list, which is naquada.

possible fix: make bee produce mystery comb and tell centrifuge to generate random material, if mechanics are bugged that bee cant make them or something.

**Comment by Buuz135** [comment]
I PR that fix a long time ago, I will fix it for the next version. A bee has a comb limit but a comb can produce "infinite" types.

**Comment by Buuz135** [comment]
Fixed in 2.3.1 but only when processed in a Forestry centrifuge, GT ones doesn't support more than 6 types of output
