### ISSUE TITLE
[reopen] for #231 Gregtech Unification.cfg shall set ingotDarkSteel unification target to EnderIO

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#245]
### `config/Gregtech/Unification.cfg` now has conflicting entries:
```yaml
enderio {
#Line 8607
        B:ingotDarkSteel_false=true
        B:ingotDarkSteel_true=false
```
Witch still cause Dark Steel ingots to be unified into a Gregtech item, since @Blood-Asp fixed it as he added a default unification target to EnderIO for `ingotDarkSteel` in commit [Blood-Asp/GT5-Unofficial@f6fc2a6](https://github.com/Blood-Asp/GT5-Unofficial/commit/f6fc2a6df60811b84bb929560921b02095cc035e#diff-bb397a179e753982e334fab8de1fbbedR1799)

Also, @tterrag1098 fixed newer versions of EnderIO via SleepyTrousers/EnderIO@d98be8d to use OreDictionary names within **all** EnderIO recipes.

##### TODO:
- [x] Change `B:ingotDarkSteel_true=false` to `B:ingotDarkSteel_true=true` and remove ` B:ingotDarkSteel_false=true` from the `enderio` section of `config/Gregtech/Unification.cfg`
and optionally
- [x] Update EnderIO to a version with fixed OreDictionary recipes.

**Comment by Buuz135** [comment]
Fixed in 2.3.1
