### ISSUE TITLE
Gregtech transformers no longer accept IC2-EU or connect to IC2 cables

### ISSUE THREAD

**Issue by aerospark** [Beyond-Reality/BeyondRealityModPack#248]
Gregtech transformers no longer accept EU or connect to IC2 cables,

I'm 99% sure this didn't happen before 2.3, probably ic2-api related

**Comment by Dyonovan** [comment]
You need to connect a Gregtech transformer to a ic2 energy storage block. ie: mfe, mfsu

From the gregtech wiki:

http://ftb.gamepedia.com/GregTech_5/Electricity#Energy_conversions

To convert IC2 EU into GT5 EU, simply connect (read put directly adjacent) a GT transformer input to an IC2 Energy Source output side. This means connecting the output dot of a IC2 transformer/storage block to the input dot of a GT transformer.
