### ISSUE TITLE
Electric blast furnace is eating aluminium

### ISSUE THREAD

**Issue by akkiosoregan** [Beyond-Reality/BeyondRealityModPack#249]
Electric blast furnace is accepting aluminium to cook and using power but not giving back ingots.  The furnace then needs to be hit with rubber hammer to accept anything again.  The furnace cooks steel fine and it is not a power issue as I have it hooked to 8 lv steam turbines via battery buffers with 4 lv energy hatches.  It's not a maintenance issue because I'm using duct tape on the machine. I have also tried using output buses and hatches with the same result.  As far as I can tell it's specifically only affecting aluminium.

**Comment by Dyonovan** [comment]
The fact that you need to restart the Blast Furnace with a hammer means it isnt able to finish the processing of the Aluminium. When this happens, greg eats whatever it is trying to process. The issue is with your setup.
