### ISSUE TITLE
[Request] Add chisel2 worldgen dusts to gregtech (have minetweaker code)

### ISSUE THREAD

**Issue by aerospark** [Beyond-Reality/BeyondRealityModPack#250]
Hey, one of the biggest things that triggers my OCD is the fact that chisel2 worldgen (which is everywhere) can't be processed in any way, despite having "proper" mineral names.

I've created a little addition to the gregtech.zs minetweaker script:
https://gist.github.com/aerospark/1655a57010d1858ee89a

**Here's how it works:**
implement dacite dust (already in gregtech but unimplemented)
implement rhyolite dust (already in gregtech but unimplemented)
steal greywacke dust item (unused and unimplemented) and rename to andesite dust
steal emery dust item (unused and unimplemented) and rename to diorite dust
Andesite + macerator = andesite dust
Diorite + macerator = diorite dust
granite + macerator = impure red granite dust (chisel granite is red)

(Based on wikipedia)
3x andesite dust + centrifuge = 100% chance (1x silicon dioxide, 1x dacite dust), 5% chance chipped yellow garnet, 6% chance impure pile of glauconite dust

3x diorite dust + centrifuge = 100% chance (1x biotite dust, 1x silicon dioxide) 5% chance chipped olivine, 3% chance impure pile of ilmenite dust

2x dacite dust + centrifuge = 100% chance (1x biotite dust, 1x rhyolite dust)

4x rhyolite dust + centrifuge = 100% chance (1x biotite dust, 4x silicon dioxide)

<br><br>
It's tested and working great on my server, just thought I'd put it here. (Can't really create a pull request until the repo is updated to 2.3.0b **wink wink nudge nudge**)

*Oh, I also plan on implementing the galacticraft stuff (ex mars cobblestone) because it also has no dust/processing*

**Comment by Dyonovan** [comment]
Hint taken lol

Repo is updated go ahead and push a commit :)
