### ISSUE TITLE
Add Fanver Beyond Reality resource pack as optional download to ATLauncher

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#254]
@artdude543 and I packaged a customized Soartex Fanver Modded texture pack for Beyond Reality.

Please add the CDN Download URI to ATLauncher as a resource pack option:
http://soartex.cursecdn.com/fanver/modded/1.7.x/modpacks/atlauncher/Fanver_Beyond_Reality.zip

**Comment by Dyonovan** [comment]
Added in 2.3.1
