### ISSUE TITLE
More gregtech worldgen processing

### ISSUE THREAD

**Issue by aerospark** [Beyond-Reality/BeyondRealityModPack#255]
Ok so similar to #250, I'd like to add even more worldgen to the macerator/centrifuge/electrolyzer. Ideally every block that generates in the world should be processable in some way. Gregtech does a fairly good job with most things, but some things still remain "purely cosmetic." despite having real-world mineral names

I'm currently working to add these on my own server, but I'd like to also submit them as another pull request when I finish. The main problem is: how are intermediary items (Dusts) added?

Normally when you macerate a type of stone, you get 1 "impure pile" of that stone's dust. (Ex red granite gives you impure pile of red granite dust)
Now, if I'm going to be adding say galacticraft "Asteroid rock" to the macerator, I'd need to create a new item "Impure pile of asteroid dust." for the macerator to output. This can easily be done using JSON and tterag/CustomThings, but apparently this can be done with something already in BR?

**Here's a list of all worldgen that can't be processed:** (Update as I go)
3 galacticraft "asteroid rock" types
galacticraft moon dirt, moon rock, moon turf
galacticraft mars rock, mars sub-surface rock, mars stone
chisel2 worldgen should be updated to use proper "impure" dust piles
all botania stone (maybe)
6 railcraft worldgen stone types

<br>
To reiterate, all of these should be processable by appropriate-tier gregtech machines, based on wikipedia or other 'scientific' sources. I want to stay as "realistic" as possible because gregtech does a fantastic job of that

**Comment by Dyonovan** [comment]
Ok after talking it over with the team, I am going to have to say no to this packwide. Of course you are free to change your server anyway you want :)

Thanks for the work though.

**Comment by aerospark** [comment]
Well all I can say is I hope you all reconsider. I know a lot of people would be interested in this sort of thing and it would be intentionally designed to match the preexisting stone processing. I'm not trying to "make things easier" It's just when a block has a real-world name you kinda expect gregtech to be able to process it, even if it needs a high tier machine
