### ISSUE TITLE
Crash when looking a bee mutation on NEI

### ISSUE THREAD

**Issue by kofteistkofte** [Beyond-Reality/BeyondRealityModPack#256]
In version 2.3.1, when I looking any gendustry bee mutation on NEI, game crashes.
crash log
http://pastebin.com/bcJ3KUqE

**Comment by leagris** [comment]
Same action cause same crash:
https://gist.github.com/leagris/fbb1a1dfbb5f890c8379

**Comment by Shoulon** [comment]
https://github.com/bdew/gendustry/issues/103

**Comment by Buuz135** [comment]
Fixed in 2.3.1b
