### ISSUE TITLE
Gregtech steel ingots will not craft nuggets

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/BeyondRealityModPack#263]
The railcraft steel can craft nuggets (metals chest converts GT steel to railcraft, but GT unification grabs i back real quick). Gregtech Steel is not crafting nuggets, you need to use a fluid solidifier and mold.

**Comment by wasteandglory** [comment]
Nope just toss a ingot into a furnace to get your GT nuggets

**Comment by Dominance** [comment]
Is there a specific recipe that uses railcraft / GT nuggets that is not ore dictionary specific?

**Comment by Buuz135** [comment]
Yes you can get steel nuggets. https://gyazo.com/2112a46228f897103c41dc96526b6778
