### ISSUE TITLE
Forestry Ores in 2.3.2

### ISSUE THREAD

**Issue by kofteistkofte** [Beyond-Reality/BeyondRealityModPack#264]
Forestry ore generation is turned on in 2.3.2.

**Comment by Dyonovan** [comment]
This is intended and it should have always been turned off as Gregtech supplies the ores.

**Comment by JasonMcRay** [comment]
@Dyonovan I think @kofteistkofte meant that they are enabled in 2.3.2, when they should not be.

**Comment by Dyonovan** [comment]
Woops. My bad.

**Comment by Dominance** [comment]
Fixed 2.3.3
