### ISSUE TITLE
Crash on world generatoin

### ISSUE THREAD

**Issue by RamboRambowski** [Beyond-Reality/BeyondRealityModPack#266]
I was exploring the End in version 2.3.2 and got the following server crash:

http://pastebin.com/acReRnnq

I have added three mods on top of the official mod list:

Fastcraft version 21
AromaCore
AromaBackup

**Comment by Dyonovan** [comment]
Talked to Chylex (hardcore ender expansion) and he says its a random structure gen bug that's near impossible to reliably replicate.

He knows about it. You should be able to just reboot without issues
