### ISSUE TITLE
Forestry backpacks aren't working, and GT ores aren't rendering until block update

### ISSUE THREAD

**Issue by pfchrist** [Beyond-Reality/BeyondRealityModPack#267]
Forestry backpacks (digger & miners) seemed to of stopped working.  The miner's at least hasn't picked up any ores since updating.

Also, I think it is a known/fixed GT issue, but GT ores show up as smoothstone until block update.   I think there is a new version that addresses that.

**Comment by ohlookitsben** [comment]
Can confirm GT 5.08.23 fixes ore rendering.

**Comment by TheMilso** [comment]
I am also getting the backpack issue.
Users can remove items from backpacks placed in prior to update but can not be placed back into bags.

**Comment by TheMilso** [comment]
Deleting the backpack config files and let them rebuild seems to fix the backpack issue.  Not sure if anything is missing from them yet.

**Comment by Dominance** [comment]
Should be fixed up now.

**Comment by Dominance** [comment]
Fixed 2.3.3
