### ISSUE TITLE
GregTech 5.08.22 does not render ores correctly until block receives an update

### ISSUE THREAD

**Issue by ohlookitsben** [Beyond-Reality/BeyondRealityModPack#268]
Blocks render with wierd (reminiscent of hiddenores=true) stone texture and gt.blockores.0.name tooltip in Waila. This texture disappears when the block is updated eg. adjacent block mined or torch placed.

Scanning forums suggests this appeared in 5.08.20. Updating to 5.08.23 resolves this issue and ores render correctly. GT ores in the nether also render with this stone texture.

**Comment by ohlookitsben** [comment]
Sorry just realised #267 was a double whammy and this issue already exists.

**Comment by Dominance** [comment]
Fixed 2.3.3
