### ISSUE TITLE
compact water turbines not working right

### ISSUE THREAD

**Issue by akkiosoregan** [Beyond-Reality/BeyondRealityModPack#269]
The compact water turbines are not outputting the proper energy amounts. The LV is outputting 16eu/t, the MV - 128eu/t, the HV - 128eu/t, and the EV - 2048eu/t.  According to the mods curse page it should be LV- 8eu/t, MV-64eu/t, HV-512eu/t, and EV-4096eu/t. I don't know if you tweaked the outputs but the HV should be higher than the MV.

**Comment by Dominance** [comment]
Well considering that the mod for some reason doesn't generate a config. there is nothing anyone could of done to change it. The issue is better placed here https://github.com/gigabit101/CompactWaterTurbines/issues As I am not sure as of yet for the reason for its addition. Seems redundant to me.
