### ISSUE TITLE
Pneumaticraft plants dont spawn

### ISSUE THREAD

**Issue by LukeWUK** [Beyond-Reality/BeyondRealityModPack#271]
All Pneumaticraft plants no longer spawn in my latest version of the pack (server), set to 0.0 in the configs. Before I explore too much further I would like to check that is intended?

**Comment by Dominance** [comment]
Im not 100% sure if its included in this version or not. But I believe there is now oils and a mixing block. So the way you attain the plastics have changed. Please verify via NEI.

**Comment by Dominance** [comment]
Yeah stuff changed in mod look it up with in game wiki press " I "
