### ISSUE TITLE
Crash everytime when I got full inventory in creative+

### ISSUE THREAD

**Issue by krielk** [Beyond-Reality/BeyondRealityModPack#272]
Game crashes everytime when you add item from nei to main inventory when it's full (creative+ inventory may be empty)
Crash report: http://pastebin.com/cenk7g9p

**Comment by Dominance** [comment]
Not sure just use normal creative mode for now. Hopefully a update will fix it.

**Comment by Dominance** [comment]
This happens when you have a full inv and right click to add items. Its a NEI issue not a mod pack one. Just dont fill your inv up and try to add more.
