### ISSUE TITLE
Bugs and Suggestion 

### ISSUE THREAD

**Issue by huneau** [Beyond-Reality/BeyondRealityModPack#273]
Hello, 

I have some ore generation bugs, it's disable into the config file but forestry ore spawn without any reason. And I have gregtech generation bug too, i'm not sure, but i think some ore don't want to spawn, I spend a lot of time to mining and i have find only mix copper veins at layer 25, sometimes poor mix coal (forget the name) and it's all. I suggest this mod : 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291128-custom-ore-generation-first-revival
You need to rebuild entirely the ore gen but I think it will work better.
(And i have disable hidden ore but it's not work, this feature make me crazy)

Next, I think you know that remain in motion and framez doesn't work, i suggest for you to integrate funkylocomotion, I try it and it's work (I don't check if you have willingly disable this 2 mod).

**Comment by Dominance** [comment]
While I am very fluent in using COG. Divergence features it. This late in the game BR will not be switching to it for multiple reasons. First its a CPU hog which effects preformance on computers more so than Gregs ore gen. Second Gregs ore gen is well executed.
The forestry issue is being taken care of in the next update.
No on funky locomotion if anything we will disable framez as it is going through a rewrite and currently is broken. Remain in motion is being updated in the next version
