### ISSUE TITLE
Suggestion for next Update

### ISSUE THREAD

**Issue by Gohu29** [Beyond-Reality/BeyondRealityModPack#274]
Hello, I think you forgot to remove industrial diamond recipe from unifier. Use this it's so cheat and make Gregtech's recipe useless.
http://imgur.com/euCZiEr

We can get free energy with "RF to EU convertor" And bridge with "Eu consumer and Rf producer".
Like that:
http://imgur.com/s8AI01N

And finally, player report to me we can smelt Tungsten with furnace IHL tools.

Thank you for having read it, I hope this will be resolved in the next update.

**Comment by Gohu29** [comment]
We have fix the two first point on our server.
We have change ratio of "Rf to Eu convertor", 0.5>0.25. 
And have add "gemDiamond" in Blacklist unifier's.

**Comment by Dominance** [comment]
What blocks are being used to convert RF to EU. Also Is this something enabled by default or was it enabled by your server?

**Comment by Dominance** [comment]
Also tungsten issue is fixed in latest IHL tools it seems as if there is a entire ore processing chain added to complicate things for your users :)

**Comment by Dominance** [comment]
ok found the issue the router reborn power transfer block should of NEVER been included in the game. RF and EU are two separate systems and need to stay that way. In BR this is a major design of the pack itself. Everything fixed in upcoming version
