### ISSUE TITLE
Adding to server list 

### ISSUE THREAD

**Issue by max-champlin** [Beyond-Reality/BeyondRealityModPack#275]
Could you please add beyondreality.unlimitedcraft.org:25566 to the server list please. You can verify we are an active community here unlimitedcraft.enjin.com 

Thanks in advance,
Cold_blu_ice

**Comment by Dominance** [comment]
Sorry went to check out the website. Do not actively list pay for items servers. While I totally understand the need to maintain a expensive server. We just do not support the practice here. If you can confirm that no items are banned and are able to be attained without paying for them I will add it to the list.

**Comment by max-champlin** [comment]
As far as I know yes you can get everything in game (minus creative ones
for obvious reasons)  without having to pay. And I do also believe we have
not banned anything.
