### ISSUE TITLE
When crafting pneumaticcraft items yields to high.

### ISSUE THREAD

**Issue by TheMilso** [Beyond-Reality/BeyondRealityModPack#276]
Crafting a Chamber Window, Chamber Valve,  or Pressure Chamber Interface yields 16 instead of 4.

**Comment by Dominance** [comment]
This was changed in pneumatic Craft in version 1.9.2-88 I have not looked at the recipe myself will soon.
-Rebalanced Pressure Chamber Interface recipe to not require plastic (as that's a higher tier now).

**Comment by TheMilso** [comment]
Also when i try to make the acid NEI shows fire as output and when i craft it i got nothing

**Comment by TheMilso** [comment]
looks like its fixed in next version
-Bugfix: Etching Acid recipe is borked.
PneumaticCraft-1.7.10-1.9.1-86-universal

**Comment by Dominance** [comment]
Yeah I have taken a look im going to reduce the amount back to 4 for the crafting recipes btw. Next version I will get it fixed up soon!
