### ISSUE TITLE
BR 2.3.3 Client crash on connecting server

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#277]
Crash log:
https://gist.github.com/leagris/6524faaee9f98b48a5c4

FML Client log: [big]
https://gist.githubusercontent.com/leagris/7105cef4527772014b38/raw/088ce3be6bc5db6ec86a93dc670f124860235987/fml-client-latest.log

**Comment by Dominance** [comment]
Fixed!
