### ISSUE TITLE
strange wrench sound.

### ISSUE THREAD

**Issue by TheMilso** [Beyond-Reality/BeyondRealityModPack#278]
Tested in SP and even deleted and reinstalled pack same result even on new worlds.
Every time i open inventory i get the sound of a wrench shortly after.
No really a game breaking issue but it's driving me nuts.

**Comment by Dyonovan** [comment]
Might have to do with Extra Utilities.

https://github.com/Blood-Asp/GT5-Unofficial/issues/130

**Comment by TheMilso** [comment]
yea that's the one looks like fix is to downgrade for now.
THANK YOU!!!

**Comment by TheMilso** [comment]
yep confirmed downgrading to 1.2.6 and issue is gone.

**Comment by Yann151924** [comment]
We have the same bug on our server, i made a special ressource pack to turn off the sound ( it turn off the drill sound,break sound and anvil sound).
You can download it to : http://public.mineaurion.com/Fix-Drill-Sound.zip

**Comment by Dominance** [comment]
Thanks a ton yann151924 Im going to include this in the launcher as a optional resource pack

**Comment by Yann151924** [comment]
Your welcome the issue is reported on : 

https://github.com/rwtema/extrautilities/issues/671

and on :

https://github.com/Blood-Asp/GT5-Unofficial/issues/130

**Comment by Buuz135** [comment]
Can't be fix until RWTema decides to.

**Comment by Dyonovan** [comment]
Ok looks like Bloodasp got it fixed in GT. Will be updated later today
