### ISSUE TITLE
Beyond Reality crashing after 2.3.3

### ISSUE THREAD

**Issue by Detoxii** [Beyond-Reality/BeyondRealityModPack#281]
Right after beyond reality updated to 2.3.3 I was getting crashes randomly and it usually involved the sounds that people were having which the sound fix addressed.I am now having a new crash after installing the sound fix resource pack, however, the error looks the same as before I got the sound fix. I am wondering if because the sound fix does not revert versions or anything and instead disables the playback of the sound file that maybe it didn't fix it. If anyone can have a look and see what they think then I would  appreciate it.

http://paste.atlauncher.com/view/2e6be623

**Comment by Buuz135** [comment]
Duplicated #280
