### ISSUE TITLE
Client Crash and Railcraft multiblocks disasemble

### ISSUE THREAD

**Issue by TheMilso** [Beyond-Reality/BeyondRealityModPack#283]
I keep getting a random crash to desktop.
when I log back in i find my Railcraft HP boiler and Railcraft steam ovens are not completed and i have to remove a block and replace to have them connect back up as multiblock.

**Comment by TheMilso** [comment]
Ok i have 2 steam ovens and 1 36HP boiler all within one chunk. Then i have a rock crusher at same level in different chunk. All disassemble all at y54 (will need to double check that number)

when i remove a piece and add it back it rebuilds. Last night it even exploded saying it was out of water...pipes where connected to inf water supply

I have one 19HP boiler in a different chunk and at y67 and it does not dis assemble.

Tonight i plan to move the multiblocks up to above sea level to see if it makes a difference.

**Comment by Buuz135** [comment]
The random crash is the same as #280 and the Multiblocks disasembling is caused by a chunkloading issue. Move them to the same chunk every part and should fix it

**Comment by TheMilso** [comment]
all my multiblocks are fully inside 1 chunk. learned that long time ago.
"Then i have a rock crusher at same level in different chunk" meant i had a different multiblock structure, rock crusher, in a different chunk from my boilers.

**Comment by Buuz135** [comment]
Do you have a thaumcraft lamp nearby?

**Comment by TheMilso** [comment]
Nope.
Only Lighting is the Ender IO Powered Lamps. (which by the way require a block update if they turn off before they turn on)
