### ISSUE TITLE
Unable to create nutrient distillation

### ISSUE THREAD

**Issue by TheMilso** [Beyond-Reality/BeyondRealityModPack#284]
I may be missing a config change that happened but i can not make nutrient distillation
I placed items in VAT and pumped water in.
Config and NEI both say it should work.
tried in slot 0 Heads and Rotten Flesh
Slot 1 Sugar and Nether Wart

![image](https://cloud.githubusercontent.com/assets/699986/9336355/a6883bc0-459e-11e5-8ed4-5932f157be8d.png)

**Comment by Buuz135** [comment]
Its an issue with custom items added, I will check it to fix it.

**Comment by Dominance** [comment]
Fixed for 2.3.4 https://github.com/Beyond-Reality/BeyondRealityModPack/commit/e6bc2b86a3c895fee822418faf648fc1fd7b1236 Thanks for the report as always milso!
