### ISSUE TITLE
Railcraft Steam Engines Overheating

### ISSUE THREAD

**Issue by seigfried13** [Beyond-Reality/BeyondRealityModPack#285]
Could be some kind of localized issue, but I am completely stumped.  Hope I am missing something obvious.

Railcraft Steam engines seem to be outputting at about 70% of their RF productions and are subsequently building up energy and overheating.  I am aware of the normal "equilibrium" of these engines, but despite every method I have tried to extract this power, it continues to overheat.

Quick example: Admin Steam producer->Industrial Steam engine->Emerald/Diamond Kinesis Pipes or EnderIO conduit->EnderIO capacitor bank

Engine begins producing RF and reaches a peak reading on the capacitor of ~55-60 RF, builds up to Orange/Red within a few minutes.

**Comment by Buuz135** [comment]
Thats how they work, they send RF in pulses, every time it does the animation it sends the RF/t that produces, the more RF stored the faster it works and the faster it sends. Its not persistent RF stream.
