### ISSUE TITLE
Bug Infinite liquid and hearth

### ISSUE THREAD

**Issue by Gohu29** [Beyond-Reality/BeyondRealityModPack#286]
Hello everyone we have found two bug in my server.

In first time a very easy glitch for duplicate liquid with applied.
Stock liquid in certus quartz tank, connect this with me fluid storage bus.
Put few liquid in this tank Like this.  
![image](https://cloud.githubusercontent.com/assets/13649609/9424608/58b2c3e6-48f2-11e5-856f-b56503ffff81.png)

After when you connect machines in the ouput with me fluid export bus and configurate for the liquid. 
Machine was fill infinitly with liquid. 
![image](https://cloud.githubusercontent.com/assets/13649609/9424628/0c7cd7ae-48f3-11e5-817b-f6bf62bcc979.png)

![image](https://cloud.githubusercontent.com/assets/13649609/9424603/405cdb88-48f2-11e5-9e87-80451bfd90d4.png)

You can fill tank openblock too. Make liquid ore for MEGACHEAT.

In second time, a more dificult glitch for infinite health bar with Botania.

Primary craft ring of the aesir, put it in your baubles.
![image](https://cloud.githubusercontent.com/assets/13649609/9424683/1ab4c3fc-48f5-11e5-9bcb-49daa2e95982.png)

Secondly kill yourself. Ring down in ground. Go back recover it.

When it is in your inventory drop it. You get three ring normaly. 
![image](https://cloud.githubusercontent.com/assets/13649609/9424689/8ad3d844-48f5-11e5-9e2a-956c26477d76.png)

Recraft this and put it in your baubles. and taddaaaa.
![image](https://cloud.githubusercontent.com/assets/13649609/9424695/cb7437fe-48f5-11e5-8fb9-d988c7793345.png)

At first you can have a black health bar but make this infinitly and finally you have many many health bar. 
You don't need ring of the aesir after.

Botania such bug, such lag, such glitch <3<3

**Comment by Gohu29** [comment]
Ps: Beyond reality version 2.3.3

**Comment by Buuz135** [comment]
Botania issue fixed from botania's part.
Extracell issue: https://github.com/ExtraCells/ExtraCells2/issues/222

**Comment by leagris** [comment]
Still waiting for a fix in Exctracells2 https://github.com/ExtraCells/ExtraCells2/issues/222

We should consider removing crafting recipes for these items:
- Fluid formation plane
- Fluid annihilation plane
- Fluid storage bus

It would leave fluid storage cells as the sole ME fluid storage option.

**Comment by leagris** [comment]
Fixed

**Comment by spacebuilder2020** [comment]
Great
