### ISSUE TITLE
CompactWater break balance.

### ISSUE THREAD

**Issue by shadowpho** [Beyond-Reality/BeyondRealityModPack#287]
Hello all,

Sorry for long post. TL;DR: compact water turbines are broken compared to every other way of getting energy.

We've been playing this modpack for several months now, and were very impressed with balance. Charcoal, nitro-diesel, lava, fuel, biodiesel, ic2 reactors are pretty well balanced with costs to startup, cost to run them and energy output. BigReactors are a bit easy compared to other solutions, but not terribly so.

We've been slowly advancing in GT tiers, from steam now to HV and higher tiers. Starting to go to moon\mars and fusion reactor. 

However, then we came upon compact water modpack. You build a single MV compact water and you get 128 eu/tick forever. It costs 160 some metals (base levels), and there is no fuel nor maintenance required ever. 

Then you compare this to every other machine there and MV compact water turbines come out on top without a doubt. 
nitro-diesel gives you 128 eu/tick but burns through fuel, requires a lot of investment and refinement. 
lava requires setting up equipment to transport from nether, then a lot of maintenance to move it. It also requires lots and lots of heat spreaders to get the energy out.
biodiesel requires crafting, thinking, planning, building, testing, and a tiny bit of energy.
ic2 reactors.... are lead expensive (pretty much requiring thaumcraft transmutation to lead), kinda cumbersome, dangerous, require maintenance, but can provide 256 eu/tick pretty reliably. 

Then there's MV CompactWater turbines. Requires less material then any of the above and provide same or greater energy forever with no maintenance nor care.  

I'd recommend either upping their price or downscaling their voltage. As of now they are the only energy source that will be built.

**Comment by Buuz135** [comment]
Changed recipes in 2.3.4 using Sunnarium as slowdown in the recipe.
