### ISSUE TITLE
Railcraft added super cheap passive anchor (chunk loaders)

### ISSUE THREAD

**Issue by shadowpho** [Beyond-Reality/BeyondRealityModPack#288]
http://www.railcraft.info/releases/9-6-0-0

Railcraft 9.6.0.0 added passive anchors, which are chunk loaders (for all effects and purposes). They are significantly cheaper then every other chunk loader out there already (they don't require a nether star!)

Breaks current balance.

**Comment by Dominance** [comment]
NEW: Add Passive Anchor, does not force load chunks on game load, only when visited. Recipe uses Cyan Dye for now, but will eventually use Prismarine. Not really sure what that means. We are still on a older version of railcraft as it is. When 2.3.3 came out railcrafts release window was still within the 7 days of a major release date. Which the Licence does not allow. In the next version I am sure we will test out these new loaders and see how they fit balance wise with everything else. Thanks for the heads up.

**Comment by shadowpho** [comment]
No problem :).  
Our server never goes down (1/mo or so), which effectively turns passive anchors into real chunk loaders for a significant price decrease. On our server everyone instantly built one and placed it in the base lol.

**Comment by Buuz135** [comment]
I will keep them with a recipe change, they are like the Personal Anchors.
Ref: http://railcraft.info/wiki/device:world_anchor

**Comment by Buuz135** [comment]
Reciped changed in 2.3.4 and changed the fuel it's fuel needs

**Comment by spacebuilder2020** [comment]
Prismarine is a world gen block added in 1.8 with underwater temples.
