### ISSUE TITLE
VAT distilation still not working

### ISSUE THREAD

**Issue by Dragonsmen83** [Beyond-Reality/BeyondRealityModPack#292]
The distillation recipes still don't work in the ender io vat I can still make hootch or any other recipe I went into a creative world and tried all combinations and nothing worked on 2.3.4 too

**Comment by SicklySpud** [comment]
I am having the same problem. I have done a fresh install and looked in the config, nothing appears out of the ordinary - Though I can't really read it well enough. It hasn't worked no matter what I try... Subscribed
