### ISSUE TITLE
No scrap from recycler

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#294]
I have a whole bunch (several stacks each) of stone dust, cobblestone, dirt, saplings and stuff. I shove it in a recycler and all I get is wasted energy. That seems odd, but that was how it was back in GT4. I could fix it then, but now I can't. Is there a secret way to fix this, cause I need to get something for my energy. Even if it was intentional, I want my scrap, so I would like to know how to fix it, if at all possible.

**Comment by Dominance** [comment]
Cannot say as I have not tested it in a long while. How ever are you attempting to put it in by hand or via pipes? It used to be disabled to use pipes and would require for the player to input the item directly.

**Comment by TheRailfan** [comment]
I put it in by hand. It processes it, but gives nothing in return. I also tried pipes in a test world and that still changes nothing. I have not seen anything on the internet relating to GT5 recyclers and scrap. To fix it in GT4, you have to go into the dynamic config and change easyscrap to true, but here there is nothing in the dynamic config

**Comment by Buuz135** [comment]
Basic items are blacklisted like cobble, and some cobble products. Lapis blocks, for example, they produce scrap. https://gyazo.com/59d3610302dc882907d172ddf2a3eac9

**Comment by TheRailfan** [comment]
Ok, but then how do I unblacklist them. So it is like normal IC2

**Comment by Buuz135** [comment]
config/Gregtech/Recipes.cfg Line 19846     B:easystonerecycling_true=true , set it to false.

**Comment by TheRailfan** [comment]
Right. Thank you for your help. I will see how OP it is, and if it's too much I will put it back
