### ISSUE TITLE
Botanica Rod of the Sky

### ISSUE THREAD

**Issue by Zahanffxi** [Beyond-Reality/BeyondRealityModPack#295]
When you right click whit the rod og the sky is keeps using charge till its empty and you cant hold right to stop charge so you dont take fall dammage.

**Comment by Buuz135** [comment]
That it's how it works, it launches into the sky. The durability is a progress bar of how much your up is left.

**Comment by Zahanffxi** [comment]
no you have no controll ower it you just go stright up and down to death thats it

**Comment by Buuz135** [comment]
According to Botania's Wiki:
 Rod of the Skies
The Rod of the Skies is a magical instrument with the ability to propel one in the air at fast velocity for the cost of some Mana.
To do so, one would simply hold it like a bow and watch as their momentum increases.
The rod takes a small amount of time to recharge, but during that time it'll block any fall damage, keeping the user safe.

It shoots you up to the sky, and the durability is the cooldown.

**Comment by Zahanffxi** [comment]
thats it you cant hold it like a bow it dos it automaticly you cant charge it just usses it all on one click. (not Holding it like a bow)

**Comment by PaulMadsen** [comment]
To reiterate what Zahan said, as the item exists right now it's usage does not simulate a bow as described above.  When you right click and release, the rod if the skies will launch the player up into the air until the durability is spent.  You cannot 'release' it to stop the behavior.  This behavior is different from previous versions of Botania.

**Comment by Buuz135** [comment]
It works like BR on other packs.

**Comment by Dominance** [comment]
Right on there is absolutely nothing in BR that would effect it acting differently than vanilla + Botania. Best to move the issue to there tracker.
