### ISSUE TITLE
IC2 Kinetic Steam Generator and Heat Steam Generator not accepting regular steam

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#296]
The Kinetic Steam Generator and the Heat Steam Generator will only accept ic2steam, not steam.

**Comment by Dominance** [comment]
IIRC this is a feature as IC2 Steam is considered Superheated Steam, not the same as normal steam. see http://wiki.industrial-craft.net/index.php?title=Steam_Generator. Unless this is fixed in IC2 there is nothing we can do to

**Comment by spacebuilder2020** [comment]
ok

**Comment by Dyonovan** [comment]
Agree with Dom. Looked it up and its an IC2 thing. Working as intended even though its a PITA
