### ISSUE TITLE
Forestry recipes not visible in NEI for machines and farm blocks 

### ISSUE THREAD

**Issue by buizerd** [Beyond-Reality/BeyondRealityModPack#298]
Everything is craftable, but you cannot lookup how

**Comment by Dominance** [comment]
Try without Inpure Core.

**Comment by Buuz135** [comment]
That was my bad, I disabled NeiIntegration for forestry to try use Forestry 4. Just enable the Forestry Integration in the NeiIntegration.cfg

**Comment by Dyonovan** [comment]
Fixed for next release https://github.com/Beyond-Reality/BeyondRealityModPack/commit/c8115dfbcab31bd3ffa1a4889e867cb88baf787a
