### ISSUE TITLE
Inventory tweaks "auto-refill" uses the wrong inventory slot

### ISSUE THREAD

**Issue by buizerd** [Beyond-Reality/BeyondRealityModPack#299]
For example; when an stone pickaxe breaks in slot 2, the new stone pickaxe gets placed in slot 3. Having the pickaxe in slot 9 results in the new pickaxe to be placed in the "trash slot", so I guess it has to do with the Trash slot mod.

[EDIT] Disabling trashslot-mc1.7.10-1.0.6.jar solves the issue

![image](https://cloud.githubusercontent.com/assets/8964747/10262761/4e87aa08-69d6-11e5-89cc-a0ceb81f2335.png)

**Comment by Dominance** [comment]
Fixed in https://github.com/Beyond-Reality/BeyondRealityModPack/commit/7718d400b4ac7cef34742c99eb3a956128aa31c0
