### ISSUE TITLE
Remain in Motion Crafting bug

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#300]
Recipe for Carriage Cross piece and Carriage panel is broken.  I tried the recipe shown in the remaininmotion minetweaker script, but it is not working.

**Comment by spacebuilder2020** [comment]
Fixed this bug and created a pull request.

**Comment by Dyonovan** [comment]
Thanks for the fix

**Comment by spacebuilder2020** [comment]
np
