### ISSUE TITLE
Crafting error when crafting hv capacitor using json shaped recipes

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#306]
Line #140 in config\machinemuse\recipes\mps-enderio.recipes  needs to be changed from
[  {"oredictName" : "componentWiring" }, { "registryName" : "EnderIO:itemBasicCapacitor" }, {"oredictName" : "componentWiring" } ],
to
[  {"oredictName" : "componentWiring" }, { "registryName" : "EnderIO:itemBasicCapacitor", "meta" : 0 }, {"oredictName" : "componentWiring" } ],

The old recipe results in making a lv capacitor with an octo capacitor.

I think this happened because the old recipe accepted any dmg value of the item, and all 3 ender io capacitors are the same item with different dmg values.

**Comment by leagris** [comment]
Given there is an MT script with very difficult recipes using GregTech. A clear choice should be made about difficulty crafting PowerSuits and components.
Choose witch mod.recipes suit best BeyondReality (classic) and disable all other alternatives.

Given the MPS is the most powerful suit ever, taking no damage, making you nearly invulnerable unless you carelessly meet with magical, poisonous or magical threats; I'd say stick with Gregtech recipes.

Now, let's consider materials involved with Gregtech recipes of the MPS as very ungrateful and costly. For having dealt with these as a challenge. I testify it took me 3 weeks or 40-60 hours to craft all components.

Not watering these MPS Gregtech recipes may have more folks turned away from BeyondReality.

**Comment by spacebuilder2020** [comment]
I hate to say it but I agree with you... I think the json recipes should either be removed or fixed, so you can't waste a expensive octo capacitor on a lv when intending to make a hv.

**Comment by Dyonovan** [comment]
removed json recipes https://github.com/Beyond-Reality/BeyondRealityModPack/commit/1cb6a5b0aa2608af6d8f9637c2af12b4cb547fef
