### ISSUE TITLE
Is this intended? // Downgrade to 4.1.4

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#317]
You are no longer able to make flint in a sag mill

![2015-10-19_22 30 29](https://cloud.githubusercontent.com/assets/8677143/10597921/04ec5e2e-76b1-11e5-9eb9-379296cb6b11.png)

I noticed you set all the outputs to use the ore dictionary in this comment.... Why do you need to do that... That is prob what caused the messed up sand in 3.3.3... Using the ore dictionary for outputs adds ambiguity... Basically, the machine does not know what to output, and unpredictable things happen.

https://github.com/Beyond-Reality/BeyondRealityModPack/commit/b0e2d48abe796ab9f9f076c68370b50dcd61bd2a

**Comment by Dyonovan** [comment]
Wasnt us who did that. That was ender io. The file you are looking at gets created everytime by ender io

**Comment by Dominance** [comment]
This is clearly set correctly https://github.com/Beyond-Reality/BeyondRealityModPack/blob/4ec12895c4445c96644578f5274c88200600d060/BR1710/config/enderio/SAGMillRecipes_Core.xml#L298 And the https://github.com/Beyond-Reality/BeyondRealityModPack/blob/4ec12895c4445c96644578f5274c88200600d060/BR1710/config/enderio/SAGMillRecipes_User.xml Is not over writing them. Please try to delete your enderIO file and let it generate by mod defaults to see if its a mod issue.

**Comment by spacebuilder2020** [comment]
This is happening on the server I am playing on.  I don't have access to those files.  However, I will test it on my client and see if it fixes it.

**Comment by spacebuilder2020** [comment]
Ok, so adding 
    <recipe name="Gravel" energyCost="2400" >
      <input>
        <itemStack oreDictionary="gravel" />
      </input>
      <output>
        <itemStack modID="minecraft" itemName="flint" />
        <itemStack modID="minecraft" itemName="flint" chance="0.1" />
        <itemStack modID="minecraft" itemName="sand" chance="0.1" />
      </output>
To the vanilla recipe group fixed the issue.

**Comment by JasonMcRay** [comment]
This is bugged in the eIO. Latest version has it changed from oreDictionary="flint" to oreDictionary="itemFlint"

**Comment by Dominance** [comment]
Thanks for the heads up jason! Will get it updated next BR version

**Comment by spacebuilder2020** [comment]
We are on 4.08 of EIO.

**Comment by leagris** [comment]
Downgraded to 4.1.4 in next version
