### ISSUE TITLE
Projected Red ores (Copper, etc) in world gen

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#322]
I was mining on 2.3.5a, and ran into Copper ore from Projected Red.  I think this is prob a bug.

![2015-10-24_00 07 56](https://cloud.githubusercontent.com/assets/8677143/10709270/8e1ac548-79e3-11e5-865e-866936c783e7.png)

**Comment by Dyonovan** [comment]
Was disabled after world was created.

**Comment by spacebuilder2020** [comment]
xD
