### ISSUE TITLE
Forestry 4 upgrade notes

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#323]
### Preparing for Forestry4

Forestry 4.x is now the new stable branch for the Forestry mod.
##### Performance improvements
- Multi-block re-factoring.
- Backward incompatible API changes.

##### Machine upgrades
Squeezer and Centrifuge now accept efficiency and speed upgrade cards similar to engines.

##### Recipes processing
It is no longer possible to centrifuge Forestry items (*combs, honey…*) into Gregtech centrifuges because current Forestry4 API. May or may not change in the future.

##### Cosmetic improvements:
- Colourful pollinated leafs.
- Render of ambient occlusion on machines.
- Chests (*Apiarist, Forester, Lepidopterologist*) now have same size and moving lead as standard chests.

### Minimal Forestry build is #789 with added compatibility for Highlands by, re-introducing plainflower
`forestry_1.7.10-4.1.0.769-unstable.jar` (*CAUTION: World changes*)

#### Before upgrading an existing world
Forestry 4 induce world changes, players will have to prepare and deal with before upgrading.

###### Alvearies
- Remove all content from Alvearies and store in chest or other container for later re-use.
- If top of alveary is made of Forestry wood slabs, replace with non-forestry wood slabs or they will be gone after upgrade. (*minor*)

###### Multifarms
- Remove all content from Multifarms and store in a chest or other container for later re-use.
- Farm configuration card will need to be redone.
- Farm sizes have changed, check for larger farms.
- Before they work again, some farms will need reforming (remove, replace block)

###### Forestry woods
All Forestry woods will disappear on upgrade. This include:
- Logs (*leafs will float in the air and decay on block update*), replace trunks with non-forestry logs or replace corresponding logs after upgrade.
- Planks (*some will disappear, some will change type*).
- Slabs (*disappear*)
- Stairs (*disappear*)
- Fences (*possibly disappear*)
- Any derived from Forestry wood (*carpenter's, multiparts,… will not render properly or disappear)

###### Villagers
Forestry forester Villagers selling wood will not be saved on 2nd world load after upgrade.
They will spam the console trying to save NBT data with invalid obsolete wood references.
It may be a good practice to remove such villagers before upgrade. They will be gone anyway.

#### Mods Compatibility upgrades
Since Forestry 4 API is backward incompatible. Some mods need to be upgraded:

- `gendustry-1.6.2.127-mc1.7.10.jar` (*Forestry4 compat*)
- `ModTweaker2-0.9.4.jar` (*Forestry4 compat*)
- `gregtech_1.7.10-5.08.32.jar` (*Forestry4 compat*)
- `neiaddons-1.12.14.40-mc1.7.10.jar` (*Forestry4 compat*)

#### `/fml confirm`
You will have missing blocks from Forestry. Just `/fml confirm` the changes.
```
 Forestry:fences2
 Forestry:planks2
 Forestry:fireproofLog1
 Forestry:fireproofLog2
 Forestry:fireproofLog5
 Forestry:fireproofLog6
 Forestry:fireproofLog3
 Forestry:fireproofLog4
 Forestry:fireproofLog7
 Forestry:fireproofLog8
 Forestry:stained
 Forestry:slabs4
 Forestry:slabs3
 Forestry:slabs2
 Forestry:slabs1
 Forestry:log3
 Forestry:log4
 Forestry:log5
 Forestry:log6
 Forestry:log1
 Forestry:log2
 Forestry:log7
 Forestry:log8
 Forestry:fireproofPlanks1
 Forestry:fireproofPlanks2
 Forestry:fireproofPlanks2
 Forestry:fireproofPlanks1
 Forestry:log2
 Forestry:log3
 Forestry:log1
 Forestry:log6
 Forestry:log7
 Forestry:log4
 Forestry:log5
 Forestry:log8
 Forestry:planks2
 Forestry:fences2
 Forestry:stained
 Forestry:slabs2
 Forestry:slabs1
 Forestry:slabs4
 Forestry:slabs3
 Forestry:fireproofLog1
 Forestry:fireproofLog5
 Forestry:fireproofLog4
 Forestry:fireproofLog3
 Forestry:fireproofLog2
 Forestry:fireproofLog8
 Forestry:fireproofLog7
 Forestry:fireproofLog6
 ```

**Comment by Buuz135** [comment]
Players that needed to check their stuff in the official BR server:
- [ ] Dyonovan
- [ ] Beef
- [ ] Goalie
- [ ] Buuz135
- [ ] Sot
- [ ] Hathadar
- [ ] Zahan
- [ ] Tony
- [ ] JodaxDK
