### ISSUE TITLE
Beyond reality update problems

### ISSUE THREAD

**Issue by potop999** [Beyond-Reality/BeyondRealityModPack#329]
I get kicked from my game upon loading my world since the update.
I get a screen "A fatal error has occured, this connection is terminated" (I'm not playing on a server) but it puts me in the multiplayer screen when I click on OK.

http://paste.atlauncher.com/view/f5e9dd91
This is from startup to me getting the error.

When I try to open my world again it works.
http://pastebin.com/yn8Wc1xs

Looking up a recipe for a forestry engines gives me a crash to desktop.

**Comment by potop999** [comment]
After looking up a recipe of anything forestry related I get a crash to desktop.
Here is the log for that:
http://paste.atlauncher.com/view/dce0b7d9

**Comment by JasonMcRay** [comment]
Disable forestry module in NEIIntegration.cfg (#328) or manually update NEIIntegration (http://minecraft.curseforge.com/projects/nei-integration/files/2261922)

**Comment by leagris** [comment]
I will push a 2.3.6a hotfix for all the above issue in a few minutes

**Comment by potop999** [comment]
That did fix it, thanks for the quick response.

The foresty miner bag doens't accept any GT ores anymore, not sure if you're aware of it.
And the Woven backpacks are now also craftable again?
