### ISSUE TITLE
Forestry planks don't work with the wand of equal trade

### ISSUE THREAD

**Issue by PaulMadsen** [Beyond-Reality/BeyondRealityModPack#342]

**Comment by leagris** [comment]
Thaumcraft 4.2.3.5 is and will stay the latest version for Minecraft 1.7.10. So I guess it will not be updated to Forestry4 API.
We will do our best to either find a workaround or let it as-is.

**Comment by spacebuilder2020** [comment]
Can you make an issue with azanor to make a patch for 1.7.10, or did he refuse?

**Comment by leagris** [comment]
Should be fixed with next update 2.3.7b Hotfix as Forestry reverted to using standard blocks instead of tiles.
