### ISSUE TITLE
Recipe for compressed cobble should require compressor

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#344]
The compressed cobble recipes should require a compressor instead of a crafting table.

Also, making bedrockium should require a implosion compressor.

**Comment by leagris** [comment]
Keep in mind compressed cobble and other ExtraUtils compressions are also early game storage space savers and decoration blocks.
Now, making higher compressions require a compressor should be good enough.
3x compression could work in an LV compressor (10EU/t)
4x compression could require an MV (40EU/t)
5x compression into HV (160EU/t)
6x and up compressions could require an implosion compressor
Implosion compressor if technically possible, should process 81 lower tier into 9 higher tier to avoid/limit spam on industrial TNT. There is no point in saving space on cobble storage if you spam your storage with gunpowder/sand/TNT/industrial TNT

Do you have ideas to replace the shaped recipe for bedrockium by an implosion compressor recipe?

**Comment by spacebuilder2020** [comment]
Yea... 4 4xCobble + 4 3xCobble + 1 diamondblock

**Comment by spacebuilder2020** [comment]
Though perhaps replace the diamondblock with an reinforced iridium plate

**Comment by leagris** [comment]
A standard Implosion compressor has only 4 input slots
The bedrockium drum already require an europium ring.
I will not push such harsh changes into 2.3.7 yet.
Lets keep this issue open to discussions on hardening compressed cobblestone and bedrockium recipes.
Players are going to have new GT toys to play with in a few days + some hardened industrial processes (plastic for cables, oil industry…)

**Comment by spacebuilder2020** [comment]
Yea... True... We should work on experimenting with gregifying different recipes later.

**Comment by Buuz135** [comment]
I will make the script for compressed cobble later today.

**Comment by shobu9** [comment]
Buuz have you made the script yet ? if not im free in the next few classes to make it...

**Comment by spacebuilder2020** [comment]
If you still have not made a script for this, I can take a shot at it.

**Comment by leagris** [comment]
Not to be done
