### ISSUE TITLE
GT5 Unofficial teleporter

### ISSUE THREAD

**Issue by PaulMadsen** [Beyond-Reality/BeyondRealityModPack#345]
It does not teleport interdimensionally as advertised.  I tried in single player.  I set the internal energy buffer to 100% and verified with a portable scanner.  I visited galacticraft mars before hand to ensure the dimension exists.  I had the dragon egg 2 blocks away from the teleporter and the internal GUI allowed me to set the dimension number.  
The teleporter will move the player/items to the coordinates in the same dimension it is in currently.
I also tested by trying to go to the nether with the same results.

**Comment by spacebuilder2020** [comment]
Is the other dimension loaded?

**Comment by spacebuilder2020** [comment]
I tested it in single player.... Works fine for me.

**Comment by PaulMadsen** [comment]
Other dimension is not loaded.  I'll try that.

**Comment by PaulMadsen** [comment]
I did some more testing.  Still have not been able to get to mars(-29), the moon(-28) or the end(1).
I attempted to chunk load both the origin in the overworld and the destination on mars.
I was able to get to the nether(-1) without chunk loading.

**Comment by leagris** [comment]
What is your server software like:
Plain Forge, KCauldron…?

**Comment by Dominance** [comment]
Inter dimensional teleporting is not a desired effect on galacticraft dimensions anyhow. That is if BR is still following the initial Planet transportation design I implemented.

**Comment by leagris** [comment]
There was no change about reaching Galacticraft dimensions. Still require GC Rockets.

As side not: BRC 2.3.7 is out right now. Check ChangeLog http://www.beyondrealitypack.com/beyond-reality-change-logs/

**Comment by PaulMadsen** [comment]
The problem goes beyond just galacticraft dimensions.  It is a problem for any dimension for which you want to use the gt teleporter interdimentionally.
In my testing I was both able and unable to get to the nether without any indication of what the differing variable was.

Sent from my iPhone

On Nov 9, 2015, at 2:36 PM, "L?a Gris" <notifications@github.com<mailto:notifications@github.com>> wrote:


There was no change about reaching Galacticraft dimensions. Still require GC Rockets.

As side not: BRC 2.3.7 is out right now. Check ChangeLog http://www.beyondrealitypack.com/beyond-reality-change-logs/

-

**Comment by Dominance** [comment]
Yeah not sure what is going on with it. But the initial design for GC restricts all placement of teleporting / tesseracts type devices. Not just using rockets to get to the dimension as there is no way to bypass that step by default

**Comment by spacebuilder2020** [comment]
I have to agree with Dom there... At least without an additional cost to go to planets.

I see the dim stucture as follows
-1, 0, 1,... Overworld dims, linked to the overworld and easy to reach.

-29 -- Moon, For example if you had a version of the nether on the moon, it would only be reachable on the moon.

etc.

**Comment by spacebuilder2020** [comment]
However, the GT teleporter is sufficiently expensive enough that it should easily be able to reach another planet.

**Comment by spacebuilder2020** [comment]
Yea... I tested it again... It won't go anywhere other than dim -1.  It even teleports the player to the overworld when a different dim is selected.  I tested it in single player.

**Comment by PaulMadsen** [comment]
I'd like to go on an adventure.  I'd like to stuff my inventory with as much stuff that I can carry, without containers,  in order to go on a one way mission to mars.  From there it is fusion or death.  The difficulty for this adventure is greater than building a rocket as it is one way.  Once I get there I am stuck, respawning will be on mars(as I recall).
I understand the reasoning behind making travel to space dimension via rocket only.  I wanted to elaborate on my desire to use a GT teleporter to go to mars.

**Comment by leagris** [comment]
Still waiting for a Fix [Up-Stream](https://github.com/Blood-Asp/GT5-Unofficial/issues/234)

**Comment by leagris** [comment]
Should be fixed for next release of GT
