### ISSUE TITLE
Deep Storage Unit 

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#350]
I think it will us Sensor(MV) and Emitter(MV) instad of Ender Pearl and Eye of Ender

The Factory Machine Block request Aluminium Plate to craft so way not use sensor and emitter

it way cheper too craft than a Quantum Chest V and hast i think the same storge 

i think so is a good way

PPP
SSS
EFE

P =  Plastic Sheet
S = Sensor (MV)
E = Emitter (MV)
F = Factory Machine Block

**Comment by leagris** [comment]
Will look into it.
Having a concurrent device that can be picked-up with its entire inventory and same capacity as a  quantum chest is an issue.
At the time this has been enabled, there where no quantum chests.
Now this look overpowered/unbalanced.
I think no recipe change can restore a balance given its extra ability to be moved with content at no cost.
At least, JABBA better barrels require a dolly and have exponentially costly upgrades.
It is something we need addressed definitely.
Thank you for your head-up.

**Comment by spacebuilder2020** [comment]
Perhaps make it require a quantum chest in the center instead of a FMB.

That way it is an upgrade to a quantum chest.

**Comment by Ldmf** [comment]
Make it endgame stuf

CCC
SSS
EQE

C = Converyor Module(IV)
S = Sensor (IV)
E = Emitter (IV)
Q = Quantum Chest IV or V

i know now it is realy expensiv but the DSU has no input limet a quantum chest has one

keep in mind it is only a idea

**Comment by spacebuilder2020** [comment]
Should not be too far end game... Should be late mid game.  Also, we should take into account the special properties of the eye of ender. Remember, this is minecraft, not reallife.

**Comment by Ldmf** [comment]
eye of ender is way to easy to get think (olny my opinion) i think senor and emitter are ok

**Comment by spacebuilder2020** [comment]
I agree it is easy, but the ingredient should be some product derived from the eye.

**Comment by Ldmf** [comment]
Emtter and Sensor are use eye of ender and only one


(english is still bad sorry)

**Comment by Dyonovan** [comment]
If I remember correctly, the following is true:

1) The dsu requires Aluminum plates for the factory block (or whatever its called). This requires an upgraded BF to make which makes it mid-game.

2) Jabba barrels can be upgraded to store a LOT and it is not that expensive to do. There is also AE systems for storage.

As this only deals with storage, I think we will leave it for now. When GT6 comes out, we will be re-doing the pack for balance and will look at it then.

**Comment by Ldmf** [comment]
it will be fine thx

**Comment by Ldmf** [comment]
New idea we have now the Assembly Line multiblock way we didn't put the DSU in it still as a upgrade 4 a Quanum Chest? only a new idea

**Comment by spacebuilder2020** [comment]
Perhaps.  However, I would want the recipe to be mostly the same ingredients (Aluminum).

It would be pretty annoying to go to HV or above just to get a DSU.

**Comment by Ldmf** [comment]
the main problem is the DSU keeps his inventory the QC dos it not
A better altenetiv is to move the DSU from aluminum to the next tear HV

**Comment by spacebuilder2020** [comment]
Well, if we do that we still need a mass storage system that is available in MV.  Barrels are ok to start with, but since we don't have Jabba, you will start running out of room to store stuff.

**Comment by spacebuilder2020** [comment]
NVR Mind. it looks like we still have Jabba.

I will support a move to HV as long as Jabba or another alternative still exists.  But I thought Jabba was getting removed (@leagris)

**Comment by Ldmf** [comment]
we have jabba storagdraws or waht it is callt AE and tha was all i think

**Comment by leagris** [comment]
StorageDrawers accept a controller.
Connect AppliedEnergistics Storage Bus to Drawer controller and get access to all drawers connected to the controller.
StorageDrawers is definitely more advanced than JABBA barrels.

**Comment by spacebuilder2020** [comment]
Ok.  I will have to look into them.  But with this in mind, I don't think there is an issue with changing the recipe.  However, what tier it should be is still unspecified.  Based on its storage capacity it should be a upgrade for the IV Quantum Chest.

However, I would love instead having a keep inventory upgrade for the Quantum Chests and disabling the DSU if we can get one of the GT modders (GT/GT++) to implement one.

**Comment by leagris** [comment]
If you Nerf DSU you also need to nerf StorageDrawers, and JABBA Barrels. Upgraded Upgraded drawers can also hold a significant amount of items.
Both Barrels and Drawers can be moved with inventory using a Dolly.
Quantum loosing inventory on move has always been a handicap in regard to concurrent storage devices. Now, Quantum Tanks have a significant edge against other fluid storages with its very high density.
With all this: I consider the current DSU, just enough gated at Aluminum smelting. I could replace Enderpearls with Gregtech Field Emitters, but I hardly find it any good. Nerfing DSU without also nerfing other storages. In the end, these are just drop-in storages, not really affecting player progression into the game.

**Comment by spacebuilder2020** [comment]
I agree there.

**Comment by Ldmf** [comment]
I am sorry, I will write longer texts in german

Also wir haben StorageDrawers, AE, Jabba, Iron Chests und die normalen Chest
für Cobblestone, Sand und Dirt haben wir immer noch Extra Utillities
In EU (Extra Utillities) haben wir auch noch Filing Cabinet für die Lagerung von Items

Alles ist ab dem ersten tag Verfügbar
Ich bin der Meinung (ACHTUNG NUR MEINE MEINUNG!!) das man es Staffeln sollte
Ich denke mir das so das man Chest von Anfang an hat genauso Iron Chest 
Jabba sollt ab lv vorhanden sein da man riesige mengen lagern kann von einer Sorte halt jeweils
StorageDrawers sollte anfang MV haben da durch den Drawer Controller und Ender IO / Logistics Pipes / Practical Logistics ein kleines ME bauen kann mit Autocraftig je nach dem welchen Mod man nehmen möchte
AE sollte ab IV erreichbar sein da es aus meiner Sicht echt hoch komplexe Technik ist und somit nicht von Anfang an zur Verfügung stehen sollte.
In IV könnte man auch die DSU packen wäre dann ab IV verfügbar und würde Upgrade für eine QC gelten.

Hinzukommt warum sollte ich zb Practical Logistics nutzen wenn es 3 mal so teuer ist wie ein ME System zu bauen? Das macht aus meiner Sicht wenig sinn.

**Comment by leagris** [comment]
Wontfix
