### ISSUE TITLE
Chamelium (OpenComputers)

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#351]
invalid Oredic and grog not craftebil 4 nanomachines

![2015-11-16_23 44 25](https://cloud.githubusercontent.com/assets/15316448/11197208/2a40a754-8cbc-11e5-81ca-27e26e4f5f0c.png)

**Comment by leagris** [comment]
ldmf what version of BR?
The invalid oredict gravel tag was a bug in EnderIO config and was fixed a while back.

**Comment by Ldmf** [comment]
BR version 2.3.7a and i us fastcraft

**Comment by leagris** [comment]
##### Fixed in current 2.3.7a release.

Either:
- Reinstall BeyondReality 2.3.7a for the fixed configuration.

or
- Replace `config/opencomputers/user.recipes` with this [user.recipes](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/config/opencomputers/user.recipes).

**Comment by Ldmf** [comment]
thx 4 the fast fix :)
