### ISSUE TITLE
Oak Wood to Charcoal in Furnace

### ISSUE THREAD

**Issue by cbeasley92** [Beyond-Reality/BeyondRealityModPack#354]
In the latest update, 2.3.7A, Oak Wood is unable to be smelted into Charcoal in a Furnace.

**Comment by spacebuilder2020** [comment]
That is a new feature of Gregtech.  However, I do think there needs to be an early game torch cause without charcoal, it becomes difficult to light up your mines.

**Comment by cbeasley92** [comment]
Do you know which version it was added? I am trying to find it in the changelog.

**Comment by spacebuilder2020** [comment]
We updated to the new gregtech in 2.3.7

**Comment by cbeasley92** [comment]
Ah, I just found it. Looks like it was under Misc Changes in 5.09.00.
Nice to know it's intentional, but sucks that it is intentional...

**Comment by leagris** [comment]
To create charcoal early game:
Build a charcoal pit, that is max 11 by 11 and 5 depth
Set ground to bricks
Walls and top must be dirt
Fill with vanilla logs
Craft an igniter and place as top center block
When pit ready it will start animating on top face
The process takes about 10 minutes.
When finished, all logs will be replaced by brittle charcoal. Use a pickaxe on it.

For early torches, use sticky resin you can get from any IC2 rubber tree with a treetap or from IC2 crop breeding stickyreeds from sugarcanes.

**Comment by JasonMcRay** [comment]
You can use sticky resin to make torches, or creosote + wool.

**Comment by cbeasley92** [comment]
Yeah torches aren't really an issue, just wanted to use charcoal for fuel. I didn't know about the Charcoal Pile Igniter, that's a really cool mechanic!

**Comment by spacebuilder2020** [comment]
True... Also, you can get slightly more than 1 charcoal per log.
