### ISSUE TITLE
Forge 1492 for BR 2.3.7.a

### ISSUE THREAD

**Issue by huneau** [Beyond-Reality/BeyondRealityModPack#355]
Hello, 

I just create a new instance with BR 2.3.7.a and forge 1558 is require but 1492 is downloaded.

**Comment by leagris** [comment]
Can you create a https://gist.github.com/ or pastebin with your logs, fml-client-latest, fml-server-latest…

**Comment by huneau** [comment]
https://gist.github.com/huneau/5a6eeefe3ccff6a8444f

Hum, just for testing I have launch without any additional mod and any problem occurs.
But when I select  : 
- apple core
- armor status hud
- bsp... core
- damage indicator
- impure core
- invotory tweaks
- journey map
- thaumcraft nei plugin
- tc node tracker

I have this issue, but don't find the expected mod.

I hope it's will help you :)

**Comment by JasonMcRay** [comment]
JourneyMap 5.1.1 requires forge 1558 (which is current recommended version).

2015-11-22 15:05 GMT+01:00 huneau <notifications@github.com>:

**Comment by leagris** [comment]
Close ATlauncher and reinstall version 2.3.7a
