### ISSUE TITLE
Botania Livingwood Twing

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#356]
Livingwood Twing uncraftebil after updat to 2.3.7b

NEI

![2015-11-24_12 52 44](https://cloud.githubusercontent.com/assets/15316448/11365938/51deb8b6-92aa-11e5-8b44-ce51864c9224.png)

Crafting Table

![2015-11-24_12 52 48](https://cloud.githubusercontent.com/assets/15316448/11365955/5f97d442-92aa-11e5-936f-84a3ca37bab7.png)

**Comment by leagris** [comment]
Reinstall or replace with this [scripts/Botania.zs](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/d12e37aefb49845fd1e4425e4880e95ca99ead2c/BR1710/scripts/Botania.zs)
