### ISSUE TITLE
2.3.7b different ae2 versions on server & client

### ISSUE THREAD

**Issue by LameGirlyCurly** [Beyond-Reality/BeyondRealityModPack#357]
On client appliedenergistics2-rv3-alpha-9.jar
and on server
appliedenergistics2-rv2-alpha-10.jar

effectively prevents players from joining :)

**Comment by leagris** [comment]
Due to a compatibility issue between thaumicenergistics and ae2 rv3-alpha-10 I had to rollback update to alpha-9
Server has to redownload pack o simply replace with the correct ae2 version
You may need to re-install your client or do the same manually.

**Comment by Dream-Master** [comment]
@leagris 
What is here the exact problem because I remember we have on my Server with a different Pack problems (lag) too.

**Comment by leagris** [comment]
Thaumic Energistics make use of AE2 internal classes and private members, so it break compatibility each time AE2 update internal structures.
The exact problem is server crash if Thaumic Energistics blocks are present and wrong version of ThaumicEnergistics for a specific AE2 build.

There is currently no ThaumicEnergistics build compatible with Applied Energistics rv3-alpha10

**Comment by Dream-Master** [comment]
But Ae rv2-stable 10 not have this problem with Thaumic Energistics 08.10.10?

**Comment by leagris** [comment]
We run rv-3 because it has pattern terminal option to register itemstack ingredient for recipes instead of ore-dictionary names.
This allow for example:
auto-crafting AE2 components referencing gt.metaitem.01:8516 (gregtech Certus Quartz) instead of ore:itemCertusQuartz, as the later will deplete your costly Charged Certus Quartz before going for the cheap Certus Quartz.

**Comment by Dream-Master** [comment]
Maybe i have to think about a switch too. Not sure if the other Ae2 Mods like Extra Cells working too.
Thanks for clarification.

**Comment by leagris** [comment]
No bug

**Comment by Dream-Master** [comment]
We usig rv3 now too. Only partly loaded Ae systems be a problem (lag)
