### ISSUE TITLE
subitems don't have damaged states

### ISSUE THREAD

**Issue by PaulMadsen** [Beyond-Reality/BeyondRealityModPack#358]
This error appears in chat whenever forestry wood planks are crafted.  Happens with and without a saw.  Tested only with blue mahoe.

**Comment by leagris** [comment]
I could not reproduce
I Uploaded updated Config scripts.
Re-download pack and tell me if it still happens

**Comment by spacebuilder2020** [comment]
I have seen this happen intermittently, but I could never find it's cause.

**Comment by spacebuilder2020** [comment]
Well, makes since... Cause gregtech tool dmg value just defines the specific item

Tool damage is stored in nbt data
