### ISSUE TITLE
Dubel Stone macerator recept and so one

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#361]
One do cobel an the other stone dust

![2015-12-19_16 00 24](https://cloud.githubusercontent.com/assets/15316448/11913613/c7ce7a66-a669-11e5-861e-c94974c57068.png)

in a furnes with Garfit you get dust or bars ^^

![2015-12-19_16 01 55](https://cloud.githubusercontent.com/assets/15316448/11913616/db030fac-a669-11e5-849f-bea1edcd0194.png)

**Comment by leagris** [comment]
Fixed in next update

**Comment by Ldmf** [comment]
ah ok thx :)
