### ISSUE TITLE
Forrestery logs

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#362]
the loogs ar plyst only in one way (marpel) i dont know if it all so

**Comment by leagris** [comment]
@Ldmf, I don't understand what you are saying/

**Comment by Ldmf** [comment]
yt link will help i hope

https://www.youtube.com/watch?v=4ql6mT-95XM

sorry my english is not the best :(

**Comment by leagris** [comment]
@Ldmf Video is Private (can not see)

**Comment by Ldmf** [comment]
it will uplod and finisht in 45 min or so sorry not the best internet :(

**Comment by leagris** [comment]
@Ldmf if unsure, tell it in your native language. Maybe I can understand with google translator :)

**Comment by Ldmf** [comment]
Ok

Also wenn man ein Foestry Holz setzen tut (Mapel) dann ist die rinden Seite immer oben und das innen leben des Baumes an der Seite egal ob man springen  platziert oder im stehen

Alternativ ist das video in 35 min oben

**Comment by leagris** [comment]
Ok, this is a known issue in Forestry.
@mezz need some extended time to rework Forestry wood from tiles to blocks with damage values. It will likely not be fixed until as: Fixing this now would be wasted with woodtype rework. See: https://github.com/ForestryMC/ForestryMC/issues/999

**Comment by Ldmf** [comment]
ah ok thx :)
