### ISSUE TITLE
Quation Forestry second princess

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#363]
Forestry: Add 0.1% chance of a second princess drop (1 every 1000 queen cycles in Beehouse/Apiary/Alveary)

is this still in it or is it too brocken?

**Comment by leagris** [comment]
For some reason it was forgotten.
It is re-enabled for next version.
You can copy change here if you need it now:
https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/config/forestry/apiculture.cfg#L10

**Comment by Ldmf** [comment]
ok thx :)
