### ISSUE TITLE
Steves Carts, Railcraft and HEE (Hardcore Ender Expansion)

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#364]
Steves Carts

This block can be craftet in a normal crafting table i think compressor make more sens

Galgadorian block also

____________________________

Railcraft

Block of Coal Coke (From Coal Coke) can be craftet in a crafting table

_________________

HEE

Endium Block can be craftet in a normal crafting table

________________

IC 2

Uranium 238 (IC2) can be craftet in a block in a craftig table

**Comment by spacebuilder2020** [comment]
Sounds like a bit of an issue, but not a major deal, cause it has been that way for months.
