### ISSUE TITLE
Creosote Oil 

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#365]
I cant burn it down to eu ther is no way even the semifluid generator cant burn it (dont ecept it at all)

**Comment by leagris** [comment]
The semi-fluid generator that accepted Creosote Oil was the Gregtech one. The standard IC2 one does not. And Gregtech 5 does not implement a semi-fluid generator.
You can still burn creosote in a Railcraft fluid firebox or in Gregtech large steam boiler. The large boiler burn thick fuels (oil, creosote...) more efficiently than light fuels.

**Comment by Ldmf** [comment]
Ah ok nei is laiing or so gg 

Nei Show that i can burn it down in a semi-fluid ^^

**Comment by leagris** [comment]
NEI says Semifluid __Boiler__ Fuels, The `Fuel Value: 8000 EU` is misleading, though it give you an order of how much Water→Steam it can boil.
![capture du 2015-12-28 16-07-55](https://cloud.githubusercontent.com/assets/1111474/12020496/74dfcae2-ad7d-11e5-88e0-4d00b1f85328.png)

#### Current Semifluid Boiler fuels in BeyondReality

| Fuel | Fuel Value |
|-------------|---------------:|
| Heavy Fuel | 160000 |
| Heavy Oil | 32000 |
| Sulfuric Heavy Fuel | 32000 |
| Raw Oil (Medium) | 24000 |
| Oil | 16000 |
| Light Oil | 16000 |
| Creosote | 8000 |
| Biomass | 8000 |
| Hemp Seed Oil | 2000 |
| Fish Oil | 2000 |
| Seed Oil | 2000 |
| Lin Seed Oil | 2000 |

**Comment by Ldmf** [comment]
ah ok the i was my mistake
