### ISSUE TITLE
Botania: Elven Trade is not adjusted to nerfing

### ISSUE THREAD

**Issue by SlashLife** [Beyond-Reality/BeyondRealityModPack#366]
The Portal of Alfheim trades mana resources for elven resources.
Mana Diamonds -> Dragonstone
Mana Pearls -> Pixie Dust
etc ...

Most unsupported items just vanish, however to avoid unnecessary losses through mind slips, uninfused raw resources have recipes for identical trade:
Diamonds -> Diamonds
Ender Pearls -> Ender Pearls
etc ...

In Vanilla Botania all of this holds true for Manasteel (made by infusing Iron Ingots in normal Botania):
(2x) Mana Steel -> (1x) Elementium
Iron Ingot -> Iron Ingot
Block of Iron -> Block of Iron

In Beyond Reality, Mana Steel is made by infusing steel, not iron, but the identical trade is still trading iron ingots and blocks while voiding steel ingots and blocks. This should be changed in accordance to the mana steel nerfing.

**Comment by Dyonovan** [comment]
Beyond Reality is supposed to be a hard pack, including losses if you do something wrong.

As this is NOT game affecting, will not be changed. Sorry

**Comment by spacebuilder2020** [comment]
Though in that case, the existing raw resource recipes should be removed cause it does not due to have some things easy and others hard.  Since BR is a hard pack, all these recipes should be removed.
