### ISSUE TITLE
power converters

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#368]
Cant craft Energy bridge and univeral carger

and some other converderts cant be craftet as well

Beyond-Reality 2.3.8

![2016-01-10_17 34 04](https://cloud.githubusercontent.com/assets/15316448/12222579/97610ed0-b7c0-11e5-91ea-f246f216e71a.png)
![2016-01-10_17 34 07](https://cloud.githubusercontent.com/assets/15316448/12222584/a40d17a0-b7c0-11e5-9bda-f708266933e4.png)

EDIT i speec only 4 producer

**Comment by leagris** [comment]
Update to 2.3.8a for fix
