### ISSUE TITLE
Nerf Buildcraft Gears to Gregtech

### ISSUE THREAD

**Issue by tiba666** [Beyond-Reality/BeyondRealityModPack#371]
i failed to use pull request :/ but was thinking about remove all normal BC gear so you only have on chose from Gregtech we are few ppl on this server there like it really hardcore lol ^^

 under buildcraft.zs

add this 
```javascript
recipes.remove(<BuildCraft|Core:woodenGearItem>);
recipes.remove(<BuildCraft|Core:stoneGearItem>);
recipes.remove(<BuildCraft|Core:ironGearItem>);
recipes.remove(<BuildCraft|Core:goldGearItem>);
recipes.remove(<BuildCraft|Core:diamondGearItem>);
```
> @leagris [edited to format code sample]

**Comment by leagris** [comment]
This would require rewriting all Buildcraft recipes for Oredict gears ingredients.
It would impair Buildcraft achievements.
Maybe other impacts.
@tiba666 Not sure it is worth hardening low tech Buildcraft, but a PR would be welcome.

**Comment by tiba666** [comment]
hmm  what about change the recipe to the same as for gregtech then ?

**Comment by tiba666** [comment]
like make gregtech gear -> buildcraft greag by recraft gregtech geer

**Comment by spacebuilder2020** [comment]
That might be a good idea.... That or changing the recipe to a shapeless interchangeable recipe that can exchange gregtech gears for BC ones but not be craftable otherwise.

**Comment by tiba666** [comment]
was the reason i said it if if for the buildcraft achievement ^:)

**Comment by leagris** [comment]
Ore-Dictionary ingredients replace those below.
#### Removed Items
```YAML
BuildCraft|Core:stoneGearItem
BuildCraft|Core:diamondGearItem
BuildCraft|Core:woodenGearItem
BuildCraft|Core:goldGearItem
BuildCraft|Core:ironGearItem
```
