### ISSUE TITLE
thuamcraft related bug caused from gergtech 

### ISSUE THREAD

**Issue by tiba666** [Beyond-Reality/BeyondRealityModPack#375]
the block of thaumium (gt) work for items and infusion with out problem but when you try to make a golem it cant do it with out it the true thaumium block (TC4)  i just used long time to get to that golem and then cant make them because this little problem there is 2 thing even provent to be able to reseach the golem or just do a craft a block of thaumium into a thaumium block in the crafting windows like the idear for the gear for BC i said in the other enchantment issues...

**Comment by leagris** [comment]
Relate to https://github.com/Blood-Asp/GT5-Unofficial/issues/358
Will be fixed in next update.
In the mean time, you can change your Thaumium block into a Thaumcraft one using Chiseel.
Or you can apply unification.cfg change from issue above.
