### ISSUE TITLE
Can't extract GT batteries from battery buffer

### ISSUE THREAD

**Issue by PaulMadsen** [Beyond-Reality/BeyondRealityModPack#376]
I have been able to move sulfuric batteries into and out of a GT battery buffer but not sodium batteries.  They can be inserted but not removed.  I have experienced this problem with Ender IO item conduits.

**Comment by JasonMcRay** [comment]
Sodium/Lithium/Cadmium batteries can't be automated. This is per design. Only ones that can be are sulfuric ones
