### ISSUE TITLE
EnderIO Farming station can crash map/server

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#382]
See:
   https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/833
   https://github.com/SleepyTrousers/EnderIO/issues/3186

**Comment by leagris** [comment]
Work-around with https://github.com/Beyond-Reality/BeyondRealityModPack/commit/72ee3e777c1dba82927ab676a3a63c3ef60a3a2e by Disabling craft of EnderIO Farming Station

**Comment by nekosune** [comment]
There will be a fix for this soon, in the mean time editing forge.cfg to remove erroring title entities SHOULD fix maps at the cost of the planter

**Comment by leagris** [comment]
Thank you, noted for the Forge erroring tile entity purge tip.

**Comment by nekosune** [comment]
Latest commit should fix
