### ISSUE TITLE
Did i miss...

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#384]
did i miss a update or so (https://github.com/Beyond-Reality/BeyondRealityModPack/commit/87a35cdc513b109c0a3d4d2aa74954bbf9233544)
ore it dit'n show in the AT luncher

**Comment by spacebuilder2020** [comment]
No idea... xD

**Comment by leagris** [comment]
This is not published yet. I wait to see if there is an updated Gregtech to come soon.

**Comment by Ldmf** [comment]
Ah ok thx :)
