### ISSUE TITLE
IC2 Tradeomat and Personal Safe

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#385]
The tradeomat does not work with the personal safe like it is supposed to.  I think this is an ic2 bug but it could be related to gregtech.

**Comment by leagris** [comment]
@spacebuilder2020 Can you please create an issue with Gregtech and IC2?
Cannot fix this with a mod-pack.

**Comment by spacebuilder2020** [comment]
Ok.  This was a long time ago on an old version so I don't even know if it is valid anymore
