### ISSUE TITLE
Server crash upon log in

### ISSUE THREAD

**Issue by lilmoefow** [Beyond-Reality/BeyondRealityModPack#388]
We just updated to 2.3.9-r2 and now everytime i log onto our server, the server crashes

http://pastebin.com/9iAUrrdF  

thats the crash log for now.. not much more info to go on. 

im just putting this here for future reference.

**Comment by spacebuilder2020** [comment]
Past bin has been deleted.

**Comment by lilmoefow** [comment]
http://pastebin.com/7TUDRqSj

**Comment by lilmoefow** [comment]
Ok so world editing out my Vis Realy Interface, Arcane crafting terminal, and that whole p2p network connecting that set up to my Applied energetics network has fixed the crash... now to set it all back up again and see what breaks.

**Comment by leagris** [comment]
So, anything new about it?

**Comment by lilmoefow** [comment]
Nothing else has occurred since.  set everything back up the way it was before the crashes started and everything is working fine..

**Comment by leagris** [comment]
@lilmoefow closing this as no more such issue.
