### ISSUE TITLE
power converters again

### ISSUE THREAD

**Issue by Ldmf** [Beyond-Reality/BeyondRealityModPack#390]
https://github.com/Beyond-Reality/BeyondRealityModPack/issues/368

Beyond Reality: 2.3.9-r2

Mods addit Fastcraft

i think you yorget the new config ^^ or by me is somthing broken...

Edit: WTF now its gone hm...

Edit: somtimes its shows the same as 368

Edit: hop i can mac e video of it

**Comment by leagris** [comment]
@Ldmf Power converters are to be scrapped entirely next update.
You don't need them any more. Connect Gregtech cable to RF machines.

**Comment by Ldmf** [comment]
ah ok than can it cosed

**Comment by spacebuilder2020** [comment]
Though i think mods like big reactors need to be balanced a bit cause you can use them to create crazy amounts of power.... from steam --> EU
