### ISSUE TITLE
Bronze Plated Blast Furnace will accept input in output slot

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#392]
When interacting with ender io item conduits, the Bronze Blast Furnace will accept items in the output slot.
![2016-03-23_22 12 55](https://cloud.githubusercontent.com/assets/8677143/14008277/b958a4a4-f144-11e5-971b-4f89e088e113.png)

**Comment by Dyonovan** [comment]
This is intentional. Greg doesn't want people to be able to automate the BBF easily.

**Comment by spacebuilder2020** [comment]
ok
