### ISSUE TITLE
Crash report loging in

### ISSUE THREAD

**Issue by Ethern8ai** [Beyond-Reality/BeyondRealityModPack#393]
Hi, my Divergence pack wont work on MultiMC (version: 0.4.11-751)

It does loads totally then before showing the starting screen crashes...

crash report: http://pastebin.com/xgVK9ygw

i tryed to test few forge versions and few others desperate attempts but i cant find out were is the problem..

And any idea why when im offline half of the packs i have wont work? most of the time MultiMC says minecraft crashed with error code -1 and Exception in thread "AE2 VersionChecker" 

thanx H.A.N.D.

**Comment by spacebuilder2020** [comment]
This is the wrong repository.  You need to make a issue at https://github.com/Beyond-Reality/Beyond-Reality-Divergence

**Comment by leagris** [comment]
as @spacebuilder2020 said, wrong repository.

**Comment by Ethern8ai** [comment]
oups sorry n thanx ^^"
