### ISSUE TITLE
Modular PowerSuits: no recipe for artificial muscle/miofiber

### ISSUE THREAD

**Issue by Aristo7** [Beyond-Reality/BeyondRealityModPack#397]
In the game, one cannot make an artificial muscle for modular powersuits.
I've dug into the scripts and in ModularPowerSuits.zs, I can see these lines:

var MyoFiberGel = <powersuits:powerArmorComponent:15>;
var ArtificialMuscle = <powersuits:powerArmorComponent:16>;

But they are missing a recipe in that script file. What were you guys intention for the recipe of these?
I went through the history of that file and I can't find any example of the recipes for these two.

Thanks a lot for the modpack, guys!

**Comment by spacebuilder2020** [comment]
I am not sure there is a use for them yet cause I spawned them in for testing and there is nothing that they add to power-suits.
