### ISSUE TITLE
Easy Stone Recycling

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#398]
A long time ago, I posted issue #294, and I followed the directions provided to allow me to get scrap from cobblestone and stone dust. I disabled easystonerecycling_true, but I am still not getting anything from my recycler. I was able to get mob grinding stuff (bones, string, meat, etc) to give scrap, but not any stone product. Is there a way to fix this? All I am doing is wasting energy

**Comment by leagris** [comment]
I wonder if stone products are also blacklisted by IC2 as well.
Anyway, recycling stone was deliberately disallowed because cobblestone/stone generators are cheap easy ⇒ Stone recycling is OP.
Alternatively I'd recommend you recycle wood slabs. You can get up to 12 per logs + some wood pulp that recycle as well. Recycle rate is 8% from whatever is not blacklisted.

**Comment by TheRailfan** [comment]
This issue has not been closed. I know it is not the way the game was designed, but its what I want to do, so please tell me how to do it, if it can be done. It is not blacklisted in IC2 or BRCore cfg files. It is set to false in Recipes.cfg

**Comment by spacebuilder2020** [comment]
Stone is blacklisted by Gretchen by default not ic2.

**Comment by TheRailfan** [comment]
I know, but I would like to re enable it. I should have removed the blacklisting with easystonerecycling_true = false

**Comment by spacebuilder2020** [comment]
There is a config file in the gregtech folder that controls that. Not sure witch on though, might be OverPoweredStuff

**Comment by TheRailfan** [comment]
In my previous post, I mentioned that I had changed the gregtech config file, but it did not work. I have checked all config files for gregtech, IC2, and BRCore, but none of them work

**Comment by spacebuilder2020** [comment]
Not sure if I can help you there then, it could be hard coded.  However, a workaround that I have found to work is forge micro-blocks.

**Comment by leagris** [comment]
Try here: https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/config/IC2.ini#L55
