### ISSUE TITLE
Dreamwood Twigs uncraftable

### ISSUE THREAD

**Issue by GitDoofus** [Beyond-Reality/BeyondRealityModPack#399]
Dreamwood twigs are currently uncraftable. Dreamwood logs are considered planks by the oredictionary, so they just produce sticks.

**Comment by leagris** [comment]
Re-download fixed [Botania.zs](https://raw.githubusercontent.com/Beyond-Reality/BeyondRealityModPack/master/BR1710/scripts/Botania.zs) to your `server/scripts` directory.
