### ISSUE TITLE
Natura specialty sticks should use standard stick shaped recipes

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#400]
as @spacebuilder2020 [commented](https://github.com/Beyond-Reality/BeyondRealityModPack/commit/635002bcd8491900cc5f89217b68542752538ee6#commitcomment-17387399):
Natura sticks should use the same standard shaped recipe as vanilla sticks.
It also means vanilla sticks would not be able to be crafted from Natura planks.

**Comment by leagris** [comment]
Unfortunately, Natura sticks using same shape ass Vanilla cause conflict issues.
Had to revert to distinct shape.

**Comment by spacebuilder2020** [comment]
xD
