### ISSUE TITLE
Gregtech Wrenches should implement standard wrench apis

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#407]
I find it rather annoying having two types of wrenches. I'd rather use my standard Gregtech wrench with Buildcraft/EnderIO/Etc and not even have the other wrenches available to craft.

Based on https://github.com/Blood-Asp/GT5-Unofficial/issues/236, it should be implemented but It does not seem to work.

**Comment by spacebuilder2020** [comment]
So, this sounds like a it is not a gregtech problem, since the ender io wrenches are able to break with shift clicking.  So I am going to test in a world with only ender io and gregtech and then open an issue on ender io.

**Comment by leagris** [comment]
Fixed in next Gregtech version https://github.com/Blood-Asp/GT5-Unofficial/issues/527
