### ISSUE TITLE
certus quartz generating in the nether instead of nether quartz.

### ISSUE THREAD

**Issue by docteurmystere** [Beyond-Reality/BeyondRealityModPack#411]
notwithstanding the config, my nether is overfilled with certus quartz (which by config should NOT generate) while nether quartz is simply not there, if not for the small ores.
edit: reproduced in ssp, gregtech config is current.

**Comment by leagris** [comment]
I could not reproduce

**Comment by swanjr** [comment]
I have had a similar issue on both single player and on my server. I cannot find any nether quart in the nether at all. Neither small ores or veins of it. I have generate about 20 worlds always the same. All the other ores appear to show up fine. I tried to modify the WorldGeneration.cfg for my server but it appears my changes just get overwritten on server start up.  I am running version 241r1. The only additional mods I added from the optional list were Biomes O Plenty, Twilight Forest, and FastCraft.

**Comment by leagris** [comment]
Would you try without Biomes O Plenty

>  I cannot find any nether quart in the nether at all
Vanilla nether quartz does not generate in Nether and this is intended.

You need to search for Gregtech Quartz ore veins that do generate in the Nether.

> I tried to modify the WorldGeneration.cfg for my server but it appears my changes just get overwritten on server start up.

If you make syntax errors in WorldGEneration.cfg it will be overwritte.
If you update/redownload the server pack it will overwrite with default BeyondReality WorldGeneration.cfg

You can come to our IRC channel [Server: irc.esper.net, channel: \#beyondreality](irc://irc.esper.net/beyondreality)
or our Discord pack-support channel:
https://discord.gg/PTAJG
for help on this issue.

**Comment by swanjr** [comment]
Yeah, it seems to be Biomes O Plenty. With that disabled I get both small and large veins of nether quartz.  

I also came a docteurmystere problem in a couple of my worlds when Biomes O Plenty was enabled. There was tons of certus quartz but no nether quartz.

As for the WorldGeneration.cfg, even if I change a value of an existing config line when I start the server it will just put the old line back in the file right next to the line I changed.

**Comment by Dominance** [comment]
You cannot edit a default line. Only toggle it on or off. You would of had to create a custom ore generation node for it to of worked. Iirc

**Comment by swanjr** [comment]
Ahh ok. Thanks.

**Comment by leagris** [comment]
Thank you @swanjr and @Dominance 
There's now little doubts, Biome-O-Plenty is gonna be dropped with next BRC update.

**Comment by swanjr** [comment]
So I found a work around. The following process seems to fix the vein nether quartz generation. 
1) Create new server with Biomes O Plenty installed/enabled.
2) Start server up and wait until fully loaded.
3) Shut server down and delete generated world folder.
4) Uninstall/disable Biomes O Plenty.
5) Start server up again and wait until loaded.
6)  Shut server down and delete generated world folder again.
7) Re-install/re-enable Biomes O Plenty.
8) Start server up again and log into world. Should be able to find Nether Quartz veins now. However, the small nether quartz still sometimes does not generate.

**Comment by spacebuilder2020** [comment]
xD

**Comment by spacebuilder2020** [comment]
I have never been a big fan of mods like Biome O Plenty due to them adding a lot of extra stuff to the world gen resulting in lots of lag when chunks are generated.  Same with highlands but not as much as Biomes O Plenty.

**Comment by swanjr** [comment]
Yeah, I think I'm going to try Highlands instead.

**Comment by leagris** [comment]
Issue is gone since BOP is now Optional
