### ISSUE TITLE
Not an issue, just a request.

### ISSUE THREAD

**Issue by Gohu29** [Beyond-Reality/BeyondRealityModPack#412]
Hello every one. 
I have a request for you. I want make my own Modpack and I want to know if i can use your mod BeyondRealityCore for ban items in space like in your moddpack.
Thanks for reading this.

**Comment by spacebuilder2020** [comment]
We can't help you if you don't give a description of your request.

**Comment by Gohu29** [comment]
Sorry for  this SpaceBuilder2020 just a mishandling.

**Comment by Dominance** [comment]
As of right now Beyond Reality Core cannot be used in packs outside of our own. The lack of a license on github means the contents are by default copyrighted. With that being said I myself have no objection on allowing for it to be used copied and distributed, Just need to get with the other two main authors @pauljoda and @Dyonovan to assign a license to the code to see what we do allow.

**Comment by pauljoda** [comment]
Eh forget licenses. Just go for it you have my permission and Dyonovans. Just don't take credit for the code. (though I wouldn't anyway as it is very poorly written for specific use cases)

**Comment by Gohu29** [comment]
Thank you very much for agreeing .
