### ISSUE TITLE
Add MiscUtilities mod

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#420]
MiscUtilities adds features for Gregtech.

See: https://github.com/draknyte1/MiscUtilities/wiki

**Comment by Dominance** [comment]
Sounds like a great addition. I'd also recommend practical Logistics.

**Comment by leagris** [comment]
Thanks to @draknyte1 for authoring and quick debugs.
This mod is now distributed with BRC.
