### ISSUE TITLE
Rebalance Bees

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/BeyondRealityModPack#423]
After reviewing production rates of Oil and Naquadah bees, there is not practical usages of their products unless heavily spamming Alveary of best traits bees.
With current setup. 72 Alveary are required to fuel a single HV generator, not accounting for processing cost.

It has also been proposed UU Bees.
This addition must be carefully balanced to provide an alternate UUMatter path helper while not replacing entirely standard UUM Production and discourage spam abuse.
IF added, it will be a very hard to get bee with picky very un-natural environment.

**Comment by Dominance** [comment]
If you do add UU matter bees. Make sure they require UU Matter to make

**Comment by leagris** [comment]
Gendustry has new useful features to tweak these bees:
https://github.com/bdew/gendustry/blob/mc1710/example_configs/example_bees.cfg#L69

**Comment by leagris** [comment]
Fixed here: https://github.com/Beyond-Reality/BeyondRealityModPack/commit/a4a68e8402e1aded2e917cc8dbd7c7a9ba90abf4
