### ISSUE TITLE
Inserting different items with SFM into Gregtech machinery fails

### ISSUE THREAD

**Issue by Parcipal** [Beyond-Reality/BeyondRealityModPack#425]
Trying to insert a Hydrogen Cell+Empty Cell into a few Chemical Reactors... It inserts all the Hydrogen Cells but fails to insert ANYTHING in the 2nd item slot in a Chemical Reactor

**Comment by leagris** [comment]
Sorry SFM bug and SFM is stalled dev/dead
Alternatively you can stick a robot arm to the chemical reactor and configure it to insert into 2nd slot.
