### ISSUE TITLE
OpenComputers computer case tiers 2 and 3 can't be crafted.

### ISSUE THREAD

**Issue by Ratysz** [Beyond-Reality/BeyondRealityModPack#427]
Likely due to requiring heat vents without any metadata, which are not possible to obtain as far as I can tell. I haven't yet found if any other recipes suffer from this as well.

**Comment by spacebuilder2020** [comment]
xD.  I think they were craftable at one point.

**Comment by leagris** [comment]
Yes Gregtech Recipes asssets from the mod are wrong: with `subID=1`
https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/recipes/gregtech.recipes#L286-L290
```yaml
case2 {
  input: [[screwStainlessSteel , "oc:materialCircuitBoardPrinted", craftingToolWrench]
          [{item="ic2.reactorVentGold", subID=1}, "oc:case1", {item="ic2.reactorVentGold", subID=1}]
          [screwStainlessSteel, "oc:circuitChip2", craftingToolScrewdriver]]
}
```
