### ISSUE TITLE
Recipe changed (non-intentional?) for Tier 1 Heavy Duty Plate (GC) in Implosion Compressor

### ISSUE THREAD

**Issue by elementography** [Beyond-Reality/BeyondRealityModPack#433]
As it says, in the change from 2.4.0-r2 to 2.4.1-r1 and beyond, the gt.blockcasings4.13.name 1163:13 has been replaced by an Engine Intake Casing in this recipe.  Perhaps more of a concern is that the Engine Intake Casing can be crafted by the recipe for the gt.blockcasings as opposed to the GT recipe.  It too has the NDT of 1163:13.  Please see the screenshots and let me know if you need any more details.

![capture 2 - 2 4 0](https://cloud.githubusercontent.com/assets/8016868/17893158/365b19c8-6977-11e6-8d13-2dee10c8ced5.PNG)
![capture 1 - 2 4 0](https://cloud.githubusercontent.com/assets/8016868/17893160/36650172-6977-11e6-9408-0cafd83809cd.PNG)
![capture 4 - 2 4 1](https://cloud.githubusercontent.com/assets/8016868/17893220/7d91e7cc-6977-11e6-92a6-90800feb030c.PNG)
![capture 3 - 2 4 1](https://cloud.githubusercontent.com/assets/8016868/17893221/7d9f95ac-6977-11e6-82d6-78bd692a52d4.PNG)

**Comment by leagris** [comment]
Thank-you @elementography will be in next release.
This updated [`galacticraft.zs`](https://raw.githubusercontent.com/Beyond-Reality/BeyondRealityModPack/aefcab5f9d17cd1d84672916053fc8a63a8e2062/BR1710/scripts/galacticraft.zs) script is safe to use in current BRC.

**Comment by elementography** [comment]
Thanks @leagris!
