### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by lilmoefow** [Beyond-Reality/BeyondRealityModPack#434]
Happens at least 3-4 times a week.   no 100% sure what is the full cause of it, might be related to someones mod spawner on the server, or just spawning the mobs in general.

http://pastebin.com/zf9qDAAU

Its being caused by ender zoo, not sure why.  It might be conflicting with Thermos, dont really know.

Would removing Ender zoo server side be safe?   I have never really been fond of that mod any way, and not having it on our server would be great.

**Comment by leagris** [comment]
@lilmoefow We can't support anything else other than pure Forge server.
Anyway you could do 2 things.
- Remove EnderZoo (no consequence for client-side)
- Open an issue to: https://github.com/CyberdyneCC/Thermos/issues

I think other modded creatures are likely to cause the same issue (think Galacticraft / HEE, though these are less common than Enderzoo.

**Comment by lilmoefow** [comment]
yeah i didnt bother reporting it to them because the crashes are not refrencing any issues with bukkit

The same crash happens with out bukkit  

SleepyTrousers/EnderZoo#137

**Comment by leagris** [comment]
There's another option.
Edit `config/forge.cfg`
```cfg
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true
```
It could prevent server crashing.

**Comment by lilmoefow** [comment]
Yeah, Lame keeps bugging me to enable that option.  Ive been told by several people to use it, no problem.

But i have also been told by several people that using that config option isn't that "safe"

I donno either way sorry for bothering you about this.
