### ISSUE TITLE
Server Crash on Start Up

### ISSUE THREAD

**Issue by lilmoefow** [Beyond-Reality/BeyondRealityModPack#439]
Not Sure why its happening it, Something to do with GT +

Crash Logs : http://pastebin.com/E59rnE40

FML Logs : http://pastebin.com/dpQah819

**Comment by leagris** [comment]
Github DNS are on a DDOS.

To allow GT++ to check his version you can add these to your `hosts` file.
If you have `root` account access:
```Bash
sudo -s
echo >>/etc/hosts -e "\n192.30.253.112  github.com www.github.com help.gitub.com"
echo >>/etc/hosts -e "\n151.101.16.133  assets-cdn.github.com github.map.fastly.net. github.map.fastly.net prod.github.map.fastlylb.net prod.github.map.fastlylb.net.
```

**Comment by leagris** [comment]
Fixed Upstream in GT++
