### ISSUE TITLE
Smelting nuggets, duplicates nuggets 1 -> 9

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/BeyondRealityModPack#440]
There's a recipe in nei in 2.4.2r1 to smelt 1 nugget into 9. It seems to work for;
Gold
Botania materials
Semi-stable nugget (extra utils)
ender io materials
thaumium
void metal

Here's me smelting 9 old nuggets into 81
http://i.imgur.com/7hX3HuY.png

**Comment by leagris** [comment]
It has been hotfixed so reload pack or only the gregtech mod server and client-side

**Comment by leagris** [comment]
Fixed
