### ISSUE TITLE
Several gendustry upgrades are not craftable

### ISSUE THREAD

**Issue by arnoleo** [Beyond-Reality/BeyondRealityModPack#442]
On the 2.4.2r1, it is impossible to craft several gendustry upgrades for industrial apiary. It's the case for all the biome modification upgrades, the sieve upgrade and the automation one. By looking in the config file, I saw that all these upgrades were using a smallGtPlasticGear in their recipes but this small gear is not displayed within NEI. I suppose that this explain why these upgrade are not craftable.

Thanks for you help

**Comment by leagris** [comment]
New config files have been hot-fixed for BRC 2.4.2-r1 and r2 and will be downloaded on re-install.
Alternatively you can download and replace [`config/Gregtech/MaterialComponents.cfg`](https://raw.githubusercontent.com/Beyond-Reality/BeyondRealityModPack/44e1e9a816d53bb8dbe4229aedd8f14430491e1a/BR1710/config/GregTech/MaterialComponents.cfg)
