### ISSUE TITLE
Blood infused iron plates for glass dagger of sacrafice cant be crafted

### ISSUE THREAD

**Issue by TeamDman** [Beyond-Reality/BeyondRealityModPack#444]
Gregtech ingot unification turns the blood infused iron into gregtech blood infused iron which cant be melted and casted into the plates.

**Comment by Dominance** [comment]
What's the blood infused iron ingot used for?

**Comment by Dominance** [comment]
Last I knew blood magic was long gone from the pack so what mod has a dagger of sacrifice?

**Comment by TeamDman** [comment]
Whoops, meant for New Horizons
