### ISSUE TITLE
GregTech-like ore generation in 1.11

### ISSUE THREAD

**Issue by plumpudding** [Beyond-Reality/BeyondRealityModPack#454]
Hello,

I was just wondering if it will be possible to have big, rare veins of specific ore types similar to GregTech ore generation in the BR 1.7 pack. 
Not that I prefer it so much, I'm just wondering if it's possible and if that is planned.

**Comment by Dominance** [comment]
Possible yes 100%

**Comment by Dominance** [comment]
Working on it! Moving to a new repo for FarScapes you can follow the progress via the commits until a official release, Versioning and Change logs are provided.
