### ISSUE TITLE
[1.11] UnifiedItems vs NeoTech Ores

### ISSUE THREAD

**Issue by plumpudding** [Beyond-Reality/BeyondRealityModPack#455]
Why did you decide to use NeoTech copper and silver instead of UnifiedItems?

**Comment by Dominance** [comment]
I think at this point ore generation like much of the pack is still very much a work in progress, subject to change.

**Comment by Dominance** [comment]
moving to a new repo. This issue is fixed as all the world gen is being redone 100%
