### ISSUE TITLE
Magic Energy Converter/Absorber Disabled

### ISSUE THREAD

**Issue by TheRailfan** [Beyond-Reality/BeyondRealityModPack#460]
The gregtech magic energy converters are disabled or uncraftable. If this is by design, which config file will allow me to re enable them? I've checked the obvious gregtech ones and the beyond reality core files, but cant seem to find how to re enable these generators. If this is supposed to be craftable, well here's the bug report. Any help is appreciated. Thank you

**Comment by leagris** [comment]
@TheRailfan You need to do Thaumcraft Researches to unlock these.
