### ISSUE TITLE
Journey Map download broken

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/BeyondRealityModPack#465]
I just went to update my pack to 2.4.4-r4 and I got this error
`[03/9/2017 19:40:14 PM] Error downloading journeymap-1.7.10-5.1.4p2-unlimited.jar from https://minecraft.curseforge.com/projects/journeymap-32274/files/2367915/download. Expected hash of 0c3daa19789a67da328437a8635c2cf3 but got 0 instead. Copied to FailedDownloads Folder. Cancelling install!
[03/9/2017 19:40:14 PM] Cannot get MD5 of **USERSDIR**\Downloads\journeymap-1.7.10-5.1.4p2-unlimited.jar as it doesn't exist`

**Comment by Dominance** [comment]
Link from https://minecraft.curseforge.com/projects/journeymap/files/2367915
Fixed current version. Just reinstall again it.
https://minecraft.curseforge.com/projects/journeymap/files/2367915/download
