### ISSUE TITLE
BR 1.7.10 2.5.1-r1 Assembly line recipes has oredict names

### ISSUE THREAD

**Issue by MechanID** [Beyond-Reality/BeyondRealityModPack#468]
Hello,
First of all i must say that this pack is amazing, playing it on private server with friends for two month, and we still have much to do. i had never such experience.

Our issue that we finally built GT 
assembly line, but recipes produced by scanner and printed books too have oredict names like gt.metaitem.01.32655.name Construction data 387

P.S. i understand that mod development is abandoned so don't worry if you have no time to investigate this issue.

![Assemblylineissue](https://user-images.githubusercontent.com/9780710/111696871-7effad80-883d-11eb-90de-90f7aa82ad00.png)

**Comment by spacebuilder2020** [comment]
This is probably a locality issue.  I have noticed that gregtech items don't have a name field.  Thus, you get artifacts like this.  I don't think there is anything that can be done about that.

**Comment by MechanID** [comment]
thanks for your response, and thank you very much for this mod pack!

**Comment by spacebuilder2020** [comment]
I am not a major contributor, I just contributed once or twice.

But agreed, this is one of my favorite modpacks.

**Comment by leagris** [comment]
It is an issue I fixed then someone-else broke it again. There is no more any significant maintenance on the GT5U repository. Most of the current work maintaining GT5 is done with the Gregtech New Norizons pack's version of Gregtech which has diverged quite alot from the version used in BeyondREality.

**Comment by MechanID** [comment]
@leagris could you please point me which your commit was fixing this issue - maybe i could rollback gt version on my server to some version where your fix is not broken yet
